/**
 * Client-side PDF rendering for board resolutions.
 *
 * Produces a single A4 PDF with a letterhead block, "certified true copy"
 * header, template-specific body paragraphs from resolutionTemplates.ts, and
 * a signature block. Text wrapping uses jsPDF's splitTextToSize so long
 * paragraphs reflow cleanly.
 */
import { jsPDF } from 'jspdf';
import type { BoardResolutionDraft } from './uiModel';
import { TEMPLATES } from './resolutionTemplates';

const LEFT = 20;
const RIGHT = 190;
const PAGE_BOTTOM = 275;
const LINE_H = 5;

function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_BOTTOM) {
    doc.addPage();
    return 22;
  }
  return y;
}

function centered(doc: jsPDF, text: string, y: number): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.text(text, pageWidth / 2, y, { align: 'center' });
}

/**
 * Wraps a paragraph to the page width and prints it starting at y.
 * Returns the new y position after the paragraph.
 */
function paragraph(doc: jsPDF, text: string, y: number): number {
  const lines = doc.splitTextToSize(text, RIGHT - LEFT) as string[];
  for (const line of lines) {
    y = ensureSpace(doc, y, LINE_H);
    doc.text(line, LEFT, y);
    y += LINE_H;
  }
  return y;
}

export async function renderBoardResolutionPdf(draft: BoardResolutionDraft): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const tpl = TEMPLATES[draft.templateId];
  const c = draft.company ?? {};
  const m = draft.meeting ?? {};
  const s = draft.signatories ?? {};

  let y = 22;

  // ── Letterhead ────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  centered(doc, (c.name ?? 'COMPANY NAME').toUpperCase(), y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  if (c.cin) {
    centered(doc, `CIN: ${c.cin}`, y);
    y += 4.5;
  }
  if (c.registeredOffice) {
    const addrLines = doc.splitTextToSize(`Registered Office: ${c.registeredOffice}`, RIGHT - LEFT) as string[];
    for (const line of addrLines) {
      centered(doc, line, y);
      y += 4.5;
    }
  }
  if (c.email || c.phone) {
    const contact = [c.email, c.phone].filter(Boolean).join(' · ');
    centered(doc, contact, y);
    y += 4.5;
  }

  // Divider
  y += 2;
  doc.setDrawColor(60, 60, 60);
  doc.line(LEFT, y, RIGHT, y);
  y += 6;

  // ── Certified true copy header ────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  const headerLine = `CERTIFIED TRUE COPY OF THE RESOLUTION PASSED AT THE MEETING OF THE BOARD OF DIRECTORS OF ${(c.name ?? 'THE COMPANY').toUpperCase()} HELD ON ${m.date ?? '__________'}${m.time ? ` AT ${m.time}` : ''} AT ${m.place ?? '__________'}`;
  y = paragraph(doc, headerLine, y);
  y += 4;

  // ── Template title + governing sections ──────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  y = ensureSpace(doc, y, 6);
  doc.text(tpl.title.toUpperCase(), LEFT, y);
  y += 5;

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  const sectionsLines = doc.splitTextToSize(
    `Under the authority of: ${tpl.governingSections.join(' · ')}`,
    RIGHT - LEFT,
  ) as string[];
  for (const line of sectionsLines) {
    y = ensureSpace(doc, y, 4);
    doc.text(line, LEFT, y);
    y += 4;
  }
  y += 4;

  // ── Body paragraphs ──────────────────────────────────────────────────
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  for (const para of tpl.body(draft)) {
    // Handle embedded newlines (e.g. enumerated lists inside a RESOLVED paragraph)
    const blocks = para.split('\n');
    for (const block of blocks) {
      y = paragraph(doc, block, y);
    }
    y += 3;
  }

  // ── Signature block ──────────────────────────────────────────────────
  y += 8;
  y = ensureSpace(doc, y, 40);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`For ${c.name ?? '__________'}`, LEFT, y);
  y += 12;

  // Signature line
  doc.setDrawColor(0, 0, 0);
  doc.line(LEFT, y, LEFT + 70, y);
  y += 4;

  const certBy = s.certifiedBy ?? {};
  doc.setFont('helvetica', 'bold');
  doc.text(certBy.name ?? '__________', LEFT, y);
  y += 4;
  doc.setFont('helvetica', 'normal');
  if (certBy.designation) {
    doc.text(certBy.designation, LEFT, y);
    y += 4;
  }
  if (certBy.din) {
    doc.text(`DIN: ${certBy.din}`, LEFT, y);
    y += 4;
  }
  y += 2;
  doc.text(`Date: ${m.date ?? '__________'}`, LEFT, y);
  y += 4;
  doc.text(`Place: ${m.place ?? '__________'}`, LEFT, y);

  // ── Footer disclaimer ────────────────────────────────────────────────
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(
    'This resolution draft is a template reproduction generated by Smartbiz AI. Please have it reviewed by a qualified Company Secretary before filing.',
    LEFT,
    290,
    { maxWidth: RIGHT - LEFT },
  );
  doc.setTextColor(0, 0, 0);

  const filename = `board-resolution-${draft.templateId}-${Date.now()}.pdf`;
  doc.save(filename);
}
