/**
 * CMA report Excel emission. Builds a multi-sheet xlsx with LIVE
 * formulas — every derived cell (gross profit, EBITDA, ratios)
 * references the input cells by row/column, so the banker can click
 * any output cell and audit the math without leaving Excel.
 *
 * Sheet layout (in order):
 *   1. Cover         — firm info, application context, methodology notes
 *   2. P&L           — historical + projected, with derived rows as formulas
 *   3. Balance Sheet — historical + projected
 *   4. Working Capital + MPBF — gap, method, eligible MPBF per year
 *   5. Ratios        — DSCR, current, quick, TOL/TNW, margins (formula-driven)
 *   6. Stress Test   — when enabled, side-by-side base vs stressed PAT/DSCR
 *   7. Term Loans    — existing + proposed schedules
 *
 * Why formulas instead of plain numbers: a banker's audit standard
 * is "click and trace". Static numbers lose credibility — looks like
 * "trust me" output. Formula-driven cells let them verify a 10×
 * difference is from a 10× input, not from us tweaking the result.
 */

import ExcelJS from 'exceljs';
import type { CmaDraft } from './uiModel';
import { MPBF_METHOD_LABELS } from './uiModel';
import type { ProjectionResult } from './projectionEngine';
import type { RatiosResult } from './ratios';
import type { MpbfResult } from './mpbf';
import { CANONICAL_ACCOUNTS, ACCOUNT_BY_KEY, type CanonicalSection } from './canonicalAccounts';
import type { StressedProjection } from './stressTest';

export interface CmaExportInput {
  draft: CmaDraft;
  projection: ProjectionResult;
  ratios: RatiosResult;
  mpbf: MpbfResult;
  stress: StressedProjection | null;
}

const RUPEE_FMT = '#,##,##0;[Red](#,##,##0);"—"';
const RATIO_FMT = '0.00';
const PCT_FMT = '0.00%';
const HEADING_FILL: ExcelJS.FillPattern = {
  type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE6F4EA' },
};
const SECTION_FILL: ExcelJS.FillPattern = {
  type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' },
};

/**
 * Build the workbook and return it as a Blob for client-side
 * download. Caller wires up the href + click + revoke.
 */
export async function buildCmaWorkbook(input: CmaExportInput): Promise<Blob> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Smartbiz Tax Assistant';
  wb.created = new Date();

  buildCoverSheet(wb, input);
  buildPLSheet(wb, input);
  buildBSSheet(wb, input);
  buildCashFlowSheet(wb, input);
  buildWcMpbfSheet(wb, input);
  buildRatiosSheet(wb, input);
  if (input.stress) buildStressSheet(wb, input);
  if ((input.draft.termLoans ?? []).length > 0) buildTermLoansSheet(wb, input);

  const buf = await wb.xlsx.writeBuffer();
  return new Blob([buf as ArrayBuffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
}

// ── Sheet 1: Cover ─────────────────────────────────────────────

function buildCoverSheet(wb: ExcelJS.Workbook, input: CmaExportInput) {
  const ws = wb.addWorksheet('Cover');
  ws.columns = [{ width: 28 }, { width: 60 }];
  ws.addRow(['CREDIT MONITORING ARRANGEMENT (CMA)']).font = { bold: true, size: 14 };
  ws.addRow([]);
  ws.addRow(['Firm', input.draft.firm?.firmName ?? '—']);
  ws.addRow(['GSTIN', input.draft.firm?.gstin ?? '—']);
  ws.addRow(['Nature of business', input.draft.firm?.businessNature ?? '—']);
  ws.addRow(['State', input.draft.firm?.state ?? '—']);
  ws.addRow(['Application context', input.draft.firm?.applicationContext ?? '—']);
  ws.addRow([]);
  ws.addRow(['Projection horizon', `${input.draft.projectionHorizon ?? 3} years`]);
  ws.addRow(['MPBF method', input.mpbf.methodLabel]);
  ws.addRow(['Working capital model', input.draft.workingCapital?.model ?? '—']);
  ws.addRow(['Stress test', input.stress ? `Enabled (sales −${input.draft.stress?.salesMissPct ?? 10}%)` : 'Disabled']);
  ws.addRow([]);
  ws.addRow(['Generated by', 'Smartbiz Tax Assistant — every formula is live; audit by clicking any output cell.']).font = { italic: true, color: { argb: 'FF6B7280' } };
  ws.getColumn(1).font = { bold: true };
}

// ── Sheet 2: P&L ───────────────────────────────────────────────

function buildPLSheet(wb: ExcelJS.Workbook, input: CmaExportInput) {
  const ws = wb.addWorksheet('P&L');
  const yearCols = input.projection.yearLabels;
  const firstP = input.projection.firstProjectedIndex;
  setupHeader(ws, 'Profit & Loss Statement (Rs. in nearest)', yearCols);

  // Track row indices for the canonical keys so derived formulas
  // can reference them. ExcelJS uses 1-based rows.
  const rowByKey = new Map<CanonicalSection, number>();
  const plOrder: CanonicalSection[] = [
    'pl_revenue', 'pl_other_income', 'pl_cogs',
    'pl_operating_expense', 'pl_depreciation', 'pl_finance_cost', 'pl_tax',
  ];

  for (const key of plOrder) {
    const acc = ACCOUNT_BY_KEY[key];
    const values = input.projection.series[key] ?? [];
    const row = ws.addRow([acc.label, ...values.map(roundFor)]);
    rowByKey.set(key, row.number);
    formatValueRow(row, firstP);
  }

  // Derived rows — formulas that reference the cells above.
  // Gross Profit = Revenue − COGS
  const grossProfitRow = ws.addRow([
    'Gross Profit',
    ...yearCols.map((_, i) => ({ formula: `${cellRef(rowByKey.get('pl_revenue')!, i + 2)}-${cellRef(rowByKey.get('pl_cogs')!, i + 2)}` })),
  ]);
  formatDerivedRow(grossProfitRow, firstP);

  // EBITDA = GP − Opex + Other Income
  const ebitdaRow = ws.addRow([
    'EBITDA',
    ...yearCols.map((_, i) => ({ formula: `${cellRef(grossProfitRow.number, i + 2)}-${cellRef(rowByKey.get('pl_operating_expense')!, i + 2)}+${cellRef(rowByKey.get('pl_other_income')!, i + 2)}` })),
  ]);
  formatDerivedRow(ebitdaRow, firstP);

  // EBIT = EBITDA − Depreciation
  const ebitRow = ws.addRow([
    'EBIT',
    ...yearCols.map((_, i) => ({ formula: `${cellRef(ebitdaRow.number, i + 2)}-${cellRef(rowByKey.get('pl_depreciation')!, i + 2)}` })),
  ]);
  formatDerivedRow(ebitRow, firstP);

  // PBT = EBIT − Finance Cost
  const pbtRow = ws.addRow([
    'Profit Before Tax',
    ...yearCols.map((_, i) => ({ formula: `${cellRef(ebitRow.number, i + 2)}-${cellRef(rowByKey.get('pl_finance_cost')!, i + 2)}` })),
  ]);
  formatDerivedRow(pbtRow, firstP);

  // PAT = PBT − Tax
  const patRow = ws.addRow([
    'Profit After Tax',
    ...yearCols.map((_, i) => ({ formula: `${cellRef(pbtRow.number, i + 2)}-${cellRef(rowByKey.get('pl_tax')!, i + 2)}` })),
  ]);
  formatDerivedRow(patRow, firstP);

  ws.getColumn(1).width = 42;
  for (let c = 2; c <= yearCols.length + 1; c++) ws.getColumn(c).width = 16;
}

// ── Sheet 3: Balance Sheet ─────────────────────────────────────

function buildBSSheet(wb: ExcelJS.Workbook, input: CmaExportInput) {
  const ws = wb.addWorksheet('Balance Sheet');
  const yearCols = input.projection.yearLabels;
  const firstP = input.projection.firstProjectedIndex;
  setupHeader(ws, 'Balance Sheet (Rs. in nearest)', yearCols);

  const sectionRow = (label: string) => {
    const r = ws.addRow([label]);
    r.font = { bold: true };
    r.getCell(1).fill = SECTION_FILL;
    return r;
  };

  const rowByKey = new Map<CanonicalSection, number>();
  const writeLine = (key: CanonicalSection) => {
    const acc = ACCOUNT_BY_KEY[key];
    const values = input.projection.series[key] ?? [];
    const r = ws.addRow([`  ${acc.label}`, ...values.map(roundFor)]);
    rowByKey.set(key, r.number);
    formatValueRow(r, firstP);
  };

  sectionRow('CURRENT ASSETS');
  (['bs_inventory', 'bs_receivables', 'bs_cash_bank', 'bs_other_current_assets'] as CanonicalSection[]).forEach(writeLine);
  const caTotalRow = ws.addRow([
    'Total Current Assets',
    ...yearCols.map((_, i) => ({ formula: sumFormula([
      rowByKey.get('bs_inventory'), rowByKey.get('bs_receivables'),
      rowByKey.get('bs_cash_bank'), rowByKey.get('bs_other_current_assets'),
    ], i + 2) })),
  ]);
  formatDerivedRow(caTotalRow, firstP);

  sectionRow('FIXED ASSETS');
  (['bs_gross_fixed_assets', 'bs_accumulated_depreciation'] as CanonicalSection[]).forEach(writeLine);
  const faTotalRow = ws.addRow([
    'Net Fixed Assets',
    ...yearCols.map((_, i) => ({ formula: `${cellRef(rowByKey.get('bs_gross_fixed_assets')!, i + 2)}-${cellRef(rowByKey.get('bs_accumulated_depreciation')!, i + 2)}` })),
  ]);
  formatDerivedRow(faTotalRow, firstP);

  sectionRow('OTHER NON-CURRENT ASSETS');
  (['bs_other_non_current_assets'] as CanonicalSection[]).forEach(writeLine);

  const totalAssetsRow = ws.addRow([
    'TOTAL ASSETS',
    ...yearCols.map((_, i) => ({ formula: `${cellRef(caTotalRow.number, i + 2)}+${cellRef(faTotalRow.number, i + 2)}+${cellRef(rowByKey.get('bs_other_non_current_assets')!, i + 2)}` })),
  ]);
  formatTotalRow(totalAssetsRow);
  ws.addRow([]);

  sectionRow('CURRENT LIABILITIES');
  (['bs_creditors', 'bs_bank_borrowing_short', 'bs_statutory_dues', 'bs_other_current_liabilities'] as CanonicalSection[]).forEach(writeLine);
  const clTotalRow = ws.addRow([
    'Total Current Liabilities',
    ...yearCols.map((_, i) => ({ formula: sumFormula([
      rowByKey.get('bs_creditors'), rowByKey.get('bs_bank_borrowing_short'),
      rowByKey.get('bs_statutory_dues'), rowByKey.get('bs_other_current_liabilities'),
    ], i + 2) })),
  ]);
  formatDerivedRow(clTotalRow, firstP);

  sectionRow('NON-CURRENT LIABILITIES');
  (['bs_term_loan', 'bs_other_non_current_liab'] as CanonicalSection[]).forEach(writeLine);
  const nclTotalRow = ws.addRow([
    'Total Non-Current Liabilities',
    ...yearCols.map((_, i) => ({ formula: sumFormula([
      rowByKey.get('bs_term_loan'), rowByKey.get('bs_other_non_current_liab'),
    ], i + 2) })),
  ]);
  formatDerivedRow(nclTotalRow, firstP);

  sectionRow('EQUITY / NET WORTH');
  (['bs_paid_up_capital', 'bs_reserves_surplus'] as CanonicalSection[]).forEach(writeLine);
  const eqTotalRow = ws.addRow([
    'Total Equity',
    ...yearCols.map((_, i) => ({ formula: sumFormula([
      rowByKey.get('bs_paid_up_capital'), rowByKey.get('bs_reserves_surplus'),
    ], i + 2) })),
  ]);
  formatDerivedRow(eqTotalRow, firstP);

  const totalLiabRow = ws.addRow([
    'TOTAL LIABILITIES + EQUITY',
    ...yearCols.map((_, i) => ({ formula: `${cellRef(clTotalRow.number, i + 2)}+${cellRef(nclTotalRow.number, i + 2)}+${cellRef(eqTotalRow.number, i + 2)}` })),
  ]);
  formatTotalRow(totalLiabRow);

  // Tie-out: TOTAL ASSETS vs TOTAL LIAB + EQUITY. Should match.
  ws.addRow([]);
  const tieOut = ws.addRow([
    'Balance check (assets − liabilities)',
    ...yearCols.map((_, i) => ({ formula: `${cellRef(totalAssetsRow.number, i + 2)}-${cellRef(totalLiabRow.number, i + 2)}` })),
  ]);
  tieOut.font = { italic: true, color: { argb: 'FF6B7280' } };
  for (let c = 2; c <= yearCols.length + 1; c++) {
    tieOut.getCell(c).numFmt = RUPEE_FMT;
  }

  ws.getColumn(1).width = 44;
  for (let c = 2; c <= yearCols.length + 1; c++) ws.getColumn(c).width = 16;
}

// ── Sheet 4: WC + MPBF ─────────────────────────────────────────

function buildWcMpbfSheet(wb: ExcelJS.Workbook, input: CmaExportInput) {
  const ws = wb.addWorksheet('WC & MPBF');
  const yearCols = input.projection.yearLabels;
  const firstP = input.projection.firstProjectedIndex;
  setupHeader(ws, `Working Capital & MPBF (${input.mpbf.methodLabel})`, yearCols);
  ws.addRow(['Working Capital Gap', ...input.projection.derived.workingCapitalGap.map(roundFor)]).eachCell((c, ci) => {
    if (ci > 1) c.numFmt = RUPEE_FMT;
  });
  ws.addRow(['MPBF (eligible bank finance)', ...input.mpbf.mpbfByYear.map(roundFor)]).eachCell((c, ci) => {
    if (ci > 1) { c.numFmt = RUPEE_FMT; c.font = { bold: true }; }
  });
  ws.addRow(['Promoter margin required', ...input.mpbf.promoterMargin.map(roundFor)]).eachCell((c, ci) => {
    if (ci > 1) c.numFmt = RUPEE_FMT;
  });
  ws.getColumn(1).width = 42;
  for (let c = 2; c <= yearCols.length + 1; c++) ws.getColumn(c).width = 16;

  // Color code projected MPBF cells.
  const mpbfRow = ws.getRow(3);
  for (let c = 2 + firstP; c <= yearCols.length + 1; c++) {
    mpbfRow.getCell(c).fill = HEADING_FILL;
  }
}

// ── Sheet 5: Ratios ────────────────────────────────────────────

function buildRatiosSheet(wb: ExcelJS.Workbook, input: CmaExportInput) {
  const ws = wb.addWorksheet('Ratios');
  const yearCols = input.projection.yearLabels;
  setupHeader(ws, 'Key Financial Ratios', yearCols);

  const rows: Array<[string, number[], string]> = [
    ['DSCR (≥ 1.5x ideal)', input.ratios.dscr, RATIO_FMT],
    ['Current Ratio (≥ 1.33x)', input.ratios.currentRatio, RATIO_FMT],
    ['Quick Ratio (≥ 1.0x)', input.ratios.quickRatio, RATIO_FMT],
    ['TOL / TNW (≤ 3.0x)', input.ratios.tolTnw, RATIO_FMT],
    ['Interest Coverage (≥ 2.0x)', input.ratios.interestCoverage, RATIO_FMT],
    ['Gross Margin %', input.ratios.grossMargin.map((v) => v / 100), PCT_FMT],
    ['EBITDA Margin %', input.ratios.ebitdaMargin.map((v) => v / 100), PCT_FMT],
  ];
  for (const [label, values, fmt] of rows) {
    const r = ws.addRow([label, ...values.map((v) => Number.isFinite(v) ? v : 0)]);
    for (let c = 2; c <= yearCols.length + 1; c++) {
      r.getCell(c).numFmt = fmt;
    }
  }
  ws.getColumn(1).width = 32;
  for (let c = 2; c <= yearCols.length + 1; c++) ws.getColumn(c).width = 16;
}

// ── Sheet 6: Stress ────────────────────────────────────────────

function buildStressSheet(wb: ExcelJS.Workbook, input: CmaExportInput) {
  if (!input.stress) return;
  const ws = wb.addWorksheet('Stress Test');
  const yearCols = input.projection.yearLabels;
  setupHeader(ws, `Stress Test — Sales miss ${input.draft.stress?.salesMissPct ?? 10}%`, yearCols);

  const writePair = (label: string, base: number[], stressed: number[], fmt: string) => {
    ws.addRow([`${label} — base`, ...base.map((v) => fmt === PCT_FMT ? v / 100 : roundFor(v))]).eachCell((c, ci) => {
      if (ci > 1) c.numFmt = fmt;
    });
    ws.addRow([`${label} — stressed`, ...stressed.map((v) => fmt === PCT_FMT ? v / 100 : roundFor(v))]).eachCell((c, ci) => {
      if (ci > 1) { c.numFmt = fmt; c.font = { color: { argb: 'FFB45309' } }; }
    });
  };

  writePair('Revenue', input.projection.series.pl_revenue ?? [], input.stress.projection.series.pl_revenue ?? [], RUPEE_FMT);
  writePair('EBITDA', input.projection.derived.ebitda, input.stress.projection.derived.ebitda, RUPEE_FMT);
  writePair('PAT', input.projection.derived.profitAfterTax, input.stress.projection.derived.profitAfterTax, RUPEE_FMT);
  writePair('DSCR', input.ratios.dscr, input.stress.ratios.dscr, RATIO_FMT);
  writePair('Current Ratio', input.ratios.currentRatio, input.stress.ratios.currentRatio, RATIO_FMT);

  ws.getColumn(1).width = 30;
  for (let c = 2; c <= yearCols.length + 1; c++) ws.getColumn(c).width = 16;
}

// ── Sheet 7: Term Loans ────────────────────────────────────────

function buildTermLoansSheet(wb: ExcelJS.Workbook, input: CmaExportInput) {
  const loans = input.draft.termLoans ?? [];
  if (loans.length === 0) return;
  const ws = wb.addWorksheet('Term Loans');
  ws.addRow(['Status', 'Lender', 'Principal (Rs.)', 'Rate %', 'Tenure (months)', 'Moratorium (months)', 'Drawn at']).font = { bold: true };
  ws.getRow(1).fill = HEADING_FILL;
  for (const ln of loans) {
    const r = ws.addRow([
      ln.status,
      ln.lender ?? '—',
      ln.principal ?? 0,
      ln.interestRatePct ?? 0,
      ln.tenureMonths ?? 0,
      ln.moratoriumMonths ?? 0,
      ln.drawnAt ?? '—',
    ]);
    r.getCell(3).numFmt = RUPEE_FMT;
    r.getCell(4).numFmt = RATIO_FMT;
  }
  ws.addRow([]);
  ws.addRow(['Projected debt service (combined across all loans)']).font = { bold: true };
  const yearCols = input.projection.yearLabels;
  setupHeader(ws, 'Year', yearCols, true);
  ws.addRow(['Principal repayment', ...input.projection.derived.termLoanPrincipal.map(roundFor)]).eachCell((c, ci) => {
    if (ci > 1) c.numFmt = RUPEE_FMT;
  });
  ws.addRow(['Interest', ...input.projection.derived.termLoanInterest.map(roundFor)]).eachCell((c, ci) => {
    if (ci > 1) c.numFmt = RUPEE_FMT;
  });
  ws.addRow(['Closing balance', ...input.projection.derived.termLoanClosingBalance.map(roundFor)]).eachCell((c, ci) => {
    if (ci > 1) c.numFmt = RUPEE_FMT;
  });
  for (let c = 1; c <= yearCols.length + 1; c++) ws.getColumn(c).width = c === 1 ? 28 : 16;
}

// ── Sheet: Cash Flow Statement (indirect method) ───────────────
//
// Derived ENTIRELY from numbers on the P&L and BS sheets, so every
// cell can reference back to its source and the banker can audit.
// Indirect method (the format banks expect for CMA):
//
//   Operating activities:
//     + PAT
//     + Depreciation (non-cash)
//     + Finance cost (added back; financing-side outflow shown separately)
//     − Tax paid (current year)
//     ± Working-capital changes (Δ receivables, Δ inventory, Δ payables, etc.)
//   = Net cash from operating activities
//
//   Investing activities:
//     − Capex (Δ in gross fixed assets, FY-to-FY)
//   = Net cash from investing activities
//
//   Financing activities:
//     − Term loan principal repayment
//     − Finance cost paid (= the add-back above, now reflected as actual outflow)
//   = Net cash from financing activities
//
//   Net change in cash = sum of all three
//   Reconciles to: Δ cash & bank on the BS
//
// We render historical + projected years side by side. The first
// historical year has no Δ working-capital row (no prior year to
// diff against) — those cells show 0 by formula.

function buildCashFlowSheet(wb: ExcelJS.Workbook, input: CmaExportInput) {
  const ws = wb.addWorksheet('Cash Flow');
  const yearCols = input.projection.yearLabels;
  const n = yearCols.length;
  const firstP = input.projection.firstProjectedIndex;
  setupHeader(ws, 'Cash Flow Statement (indirect method, Rs. in nearest)', yearCols);

  const sectionRow = (label: string) => {
    const r = ws.addRow([label]);
    r.font = { bold: true };
    r.getCell(1).fill = SECTION_FILL;
    return r;
  };

  const writeNumberRow = (label: string, values: number[]) => {
    const row = ws.addRow([`  ${label}`, ...values.map(roundFor)]);
    formatValueRow(row, firstP);
    return row.number;
  };

  // ── Operating activities ────────────────────────────────────
  sectionRow('A. CASH FLOW FROM OPERATING ACTIVITIES');

  const patRow = writeNumberRow('Profit after tax', input.projection.derived.profitAfterTax);
  const depRow = writeNumberRow('Add: Depreciation', input.projection.series.pl_depreciation ?? new Array(n).fill(0));
  const intRow = writeNumberRow('Add: Finance cost', input.projection.series.pl_finance_cost ?? new Array(n).fill(0));
  const taxRow = writeNumberRow('Less: Tax paid', (input.projection.series.pl_tax ?? new Array(n).fill(0)));

  // Working-capital changes — Δ year-over-year. Positive ΔCA = cash
  // outflow (more money locked in WC); positive ΔCL = cash inflow
  // (more vendor / statutory funding). Year 0 has no prior year
  // reference → zero.
  const wcDeltaFor = (
    series: number[] | undefined,
    sign: 1 | -1,
  ): number[] => {
    const arr = series ?? new Array(n).fill(0);
    return arr.map((v, i) => i === 0 ? 0 : sign * (arr[i - 1] - v));
  };

  const dReceivables = wcDeltaFor(input.projection.series.bs_receivables, 1);
  const dInventory = wcDeltaFor(input.projection.series.bs_inventory, 1);
  const dOtherCA = wcDeltaFor(input.projection.series.bs_other_current_assets, 1);
  const dCreditors = wcDeltaFor(input.projection.series.bs_creditors, -1);
  const dStatutory = wcDeltaFor(input.projection.series.bs_statutory_dues, -1);
  const dOtherCL = wcDeltaFor(input.projection.series.bs_other_current_liabilities, -1);

  const dRecvRow = writeNumberRow('Less: Increase in receivables', dReceivables);
  const dInvRow = writeNumberRow('Less: Increase in inventory', dInventory);
  const dOtherCARow = writeNumberRow('Less: Increase in other current assets', dOtherCA);
  const dCredRow = writeNumberRow('Add: Increase in trade payables', dCreditors);
  const dStatRow = writeNumberRow('Add: Increase in statutory dues', dStatutory);
  const dOtherCLRow = writeNumberRow('Add: Increase in other current liabilities', dOtherCL);

  // Net cash from operating activities — formula summing all the rows above.
  const operatingRefs = [patRow, depRow, intRow, taxRow, dRecvRow, dInvRow, dOtherCARow, dCredRow, dStatRow, dOtherCLRow];
  const netOperatingRow = ws.addRow([
    'Net cash from operating activities (A)',
    ...yearCols.map((_, i) => ({ formula: operatingRefs.map((r) => cellRef(r, i + 2)).join('+') })),
  ]);
  formatTotalRow(netOperatingRow);
  ws.addRow([]);

  // ── Investing activities ────────────────────────────────────
  sectionRow('B. CASH FLOW FROM INVESTING ACTIVITIES');
  // Capex = increase in gross fixed assets year-over-year. First
  // year shows 0 (no prior to diff against).
  const grossFa = input.projection.series.bs_gross_fixed_assets ?? new Array(n).fill(0);
  const capex = grossFa.map((v, i) => i === 0 ? 0 : -(v - grossFa[i - 1]));
  const capexRow = writeNumberRow('Less: Capex (increase in gross fixed assets)', capex);
  const netInvestingRow = ws.addRow([
    'Net cash from investing activities (B)',
    ...yearCols.map((_, i) => ({ formula: cellRef(capexRow, i + 2) })),
  ]);
  formatTotalRow(netInvestingRow);
  ws.addRow([]);

  // ── Financing activities ────────────────────────────────────
  sectionRow('C. CASH FLOW FROM FINANCING ACTIVITIES');
  const principalRow = writeNumberRow(
    'Less: Term loan principal repayment',
    input.projection.derived.termLoanPrincipal.map((v) => -v),
  );
  const interestPaidRow = writeNumberRow(
    'Less: Finance cost paid',
    (input.projection.series.pl_finance_cost ?? new Array(n).fill(0)).map((v) => -v),
  );
  // Change in equity (paid-up capital injection) — positive = inflow.
  const equity = input.projection.series.bs_paid_up_capital ?? new Array(n).fill(0);
  const equityChange = equity.map((v, i) => i === 0 ? 0 : v - equity[i - 1]);
  const equityRow = writeNumberRow('Add: Increase in paid-up capital', equityChange);

  const netFinancingRow = ws.addRow([
    'Net cash from financing activities (C)',
    ...yearCols.map((_, i) => ({
      formula: `${cellRef(principalRow, i + 2)}+${cellRef(interestPaidRow, i + 2)}+${cellRef(equityRow, i + 2)}`,
    })),
  ]);
  formatTotalRow(netFinancingRow);
  ws.addRow([]);

  // ── Net change in cash ──────────────────────────────────────
  const netChangeRow = ws.addRow([
    'Net increase / (decrease) in cash (A + B + C)',
    ...yearCols.map((_, i) => ({
      formula: `${cellRef(netOperatingRow.number, i + 2)}+${cellRef(netInvestingRow.number, i + 2)}+${cellRef(netFinancingRow.number, i + 2)}`,
    })),
  ]);
  formatTotalRow(netChangeRow);

  // Reconciliation: BS cash & bank delta YoY should match net change
  // calculated above (within rounding). Surface as an italic check
  // row at the bottom so the banker can see the tie.
  const cashBank = input.projection.series.bs_cash_bank ?? new Array(n).fill(0);
  const cashDelta = cashBank.map((v, i) => i === 0 ? 0 : v - cashBank[i - 1]);
  const reconcileRow = ws.addRow([
    'BS Δ cash check (should reconcile to row above)',
    ...cashDelta.map(roundFor),
  ]);
  reconcileRow.font = { italic: true, color: { argb: 'FF6B7280' } };
  for (let c = 2; c <= n + 1; c++) reconcileRow.getCell(c).numFmt = RUPEE_FMT;

  ws.getColumn(1).width = 50;
  for (let c = 2; c <= n + 1; c++) ws.getColumn(c).width = 16;
}

// ── Helpers ─────────────────────────────────────────────────────

function setupHeader(ws: ExcelJS.Worksheet, title: string, yearCols: string[], skipTitleRow = false) {
  if (!skipTitleRow) {
    const t = ws.addRow([title]);
    t.font = { bold: true, size: 13 };
    ws.addRow([]);
  }
  const headerRow = ws.addRow(['', ...yearCols]);
  headerRow.font = { bold: true };
  headerRow.eachCell((c) => { c.fill = HEADING_FILL; });
}

/** ExcelJS uses A1 notation. Convert (row, column1Based) → 'A1'. */
function cellRef(row: number, col: number): string {
  let s = '';
  let c = col;
  while (c > 0) {
    const rem = (c - 1) % 26;
    s = String.fromCharCode(65 + rem) + s;
    c = Math.floor((c - 1) / 26);
  }
  return `${s}${row}`;
}

function sumFormula(rows: Array<number | undefined>, col: number): string {
  return rows.filter((r): r is number => typeof r === 'number')
    .map((r) => cellRef(r, col))
    .join('+');
}

function roundFor(n: number): number {
  return Number.isFinite(n) ? Math.round(n) : 0;
}

function formatValueRow(row: ExcelJS.Row, firstProjectedIndex: number) {
  row.eachCell((cell, colNumber) => {
    if (colNumber > 1) {
      cell.numFmt = RUPEE_FMT;
      // Projected columns (1-based: header is col 1, so data starts at col 2;
      // firstProjectedIndex is 0-based offset into year-cols, so column
      // index for first projected = 2 + firstProjectedIndex)
      if (colNumber - 2 >= firstProjectedIndex) {
        cell.fill = HEADING_FILL;
      }
    }
  });
}

function formatDerivedRow(row: ExcelJS.Row, firstProjectedIndex: number) {
  row.font = { bold: true };
  formatValueRow(row, firstProjectedIndex);
}

function formatTotalRow(row: ExcelJS.Row) {
  row.font = { bold: true };
  row.eachCell((cell, colNumber) => {
    if (colNumber > 1) {
      cell.numFmt = RUPEE_FMT;
      cell.border = { top: { style: 'thin' }, bottom: { style: 'double' } };
    }
  });
}
