import jsPDF from 'jspdf';
import type { IncomeTaxResult } from './taxEngine';

function formatINR(n: number): string {
  const rounded = Math.round(n);
  // Indian number formatting: 1,00,000 pattern
  // toLocaleString('en-IN') may not work in all Node/jsPDF contexts,
  // so we format manually for reliability.
  const str = Math.abs(rounded).toString();
  let formatted: string;
  if (str.length <= 3) {
    formatted = str;
  } else {
    // Last 3 digits, then groups of 2
    const last3 = str.slice(-3);
    const rest = str.slice(0, -3);
    const groups: string[] = [];
    for (let i = rest.length; i > 0; i -= 2) {
      groups.unshift(rest.slice(Math.max(0, i - 2), i));
    }
    formatted = groups.join(',') + ',' + last3;
  }
  return (rounded < 0 ? '-' : '') + 'Rs. ' + formatted;
}

export function exportTaxComputationPDF(
  oldResult: IncomeTaxResult,
  newResult: IncomeTaxResult,
  fy: string,
  userName?: string,
): void {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginLeft = 20;
  const marginRight = 20;
  const contentWidth = pageWidth - marginLeft - marginRight;
  let y = 20;

  // ── Header ──────────────────────────────────────────────────────────────────
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`Tax Computation Statement \u2014 FY ${fy}`, pageWidth / 2, y, { align: 'center' });
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by Smartbiz AI Tax Assistant', pageWidth / 2, y, { align: 'center' });
  y += 6;

  const now = new Date();
  const today = `${String(now.getDate()).padStart(2, '0')}/${String(now.getMonth() + 1).padStart(2, '0')}/${now.getFullYear()}`;
  doc.text(`Date: ${today}`, pageWidth / 2, y, { align: 'center' });
  y += 6;

  if (userName) {
    doc.text(`Taxpayer: ${userName}`, pageWidth / 2, y, { align: 'center' });
    y += 6;
  }

  doc.setTextColor(0, 0, 0);
  y += 4;

  // ── Helpers ─────────────────────────────────────────────────────────────────
  function drawSectionHeader(title: string) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(title, marginLeft, y);
    y += 1;
    doc.setLineWidth(0.5);
    doc.line(marginLeft, y, pageWidth - marginRight, y);
    y += 6;
  }

  function drawRow(label: string, value: string) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(label, marginLeft + 4, y);
    doc.text(value, pageWidth - marginRight - 4, y, { align: 'right' });
    y += 6;
  }

  function drawRowBold(label: string, value: string) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(label, marginLeft + 4, y);
    doc.text(value, pageWidth - marginRight - 4, y, { align: 'right' });
    y += 6;
  }

  function checkPageBreak(needed: number) {
    if (y + needed > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      y = 20;
    }
  }

  // ── Section 1: Income Summary ───────────────────────────────────────────────
  drawSectionHeader('Income Summary');
  drawRow('Gross Income', formatINR(oldResult.grossIncome));
  drawRow('Standard Deduction (Old Regime)', formatINR(oldResult.standardDeduction));
  drawRow('Standard Deduction (New Regime)', formatINR(newResult.standardDeduction));
  if (oldResult.hraExemption > 0) {
    drawRow('HRA Exemption (Old Regime)', formatINR(oldResult.hraExemption));
  }
  if (oldResult.totalDeductions > oldResult.standardDeduction + oldResult.hraExemption) {
    drawRow(
      'Other Deductions (Old Regime)',
      formatINR(oldResult.totalDeductions - oldResult.standardDeduction - oldResult.hraExemption),
    );
  }
  y += 4;

  // ── Section 2: Old Regime ───────────────────────────────────────────────────
  checkPageBreak(60);
  drawSectionHeader('Old Regime');
  drawRow('Taxable Income', formatINR(oldResult.taxableIncome));
  drawRow('Slab Tax', formatINR(oldResult.slabTax));
  if (oldResult.rebate87A > 0) {
    drawRow('Less: Rebate u/s 87A', formatINR(oldResult.rebate87A));
  }
  if (oldResult.surcharge > 0) {
    drawRow(`Surcharge (${(oldResult.surchargeRate * 100).toFixed(0)}%)`, formatINR(oldResult.surcharge));
  }
  drawRow('Health & Education Cess (4%)', formatINR(oldResult.cess));
  drawRowBold('Total Tax (Old Regime)', formatINR(oldResult.totalTax));
  drawRow('Effective Tax Rate', `${oldResult.effectiveRate.toFixed(2)}%`);
  y += 4;

  // ── Section 3: New Regime ───────────────────────────────────────────────────
  checkPageBreak(60);
  drawSectionHeader('New Regime');
  drawRow('Taxable Income', formatINR(newResult.taxableIncome));
  drawRow('Slab Tax', formatINR(newResult.slabTax));
  if (newResult.rebate87A > 0) {
    drawRow('Less: Rebate u/s 87A', formatINR(newResult.rebate87A));
  }
  if (newResult.marginalRelief > 0) {
    drawRow('Less: Marginal Relief', formatINR(newResult.marginalRelief));
  }
  if (newResult.surcharge > 0) {
    drawRow(`Surcharge (${(newResult.surchargeRate * 100).toFixed(0)}%)`, formatINR(newResult.surcharge));
  }
  drawRow('Health & Education Cess (4%)', formatINR(newResult.cess));
  drawRowBold('Total Tax (New Regime)', formatINR(newResult.totalTax));
  drawRow('Effective Tax Rate', `${newResult.effectiveRate.toFixed(2)}%`);
  y += 4;

  // ── Section 4: Recommendation ───────────────────────────────────────────────
  checkPageBreak(30);
  drawSectionHeader('Recommendation');
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');

  const diff = oldResult.totalTax - newResult.totalTax;
  let recommendation: string;
  if (diff > 0) {
    recommendation = `New Regime saves ${formatINR(diff)}`;
  } else if (diff < 0) {
    recommendation = `Old Regime saves ${formatINR(Math.abs(diff))}`;
  } else {
    recommendation = 'Both regimes result in equal tax liability';
  }
  doc.text(recommendation, marginLeft + 4, y);
  y += 10;

  // ── Footer ──────────────────────────────────────────────────────────────────
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(130, 130, 130);
  doc.text(
    'Disclaimer: This is an estimated computation. Consult a qualified CA for official filing.',
    pageWidth / 2,
    footerY,
    { align: 'center' },
  );
  doc.text(
    `Generated on ${today} by Smartbiz AI (ai.smartbizin.com)`,
    pageWidth / 2,
    footerY + 5,
    { align: 'center' },
  );

  // ── Save ────────────────────────────────────────────────────────────────────
  doc.save(`tax-computation-FY-${fy}.pdf`);
}
