/**
 * Per-ERP deterministic column rules for ledger PDFs.
 *
 * Ledger exports come from a small number of accounting packages
 * (Tally, Busy, Marg, Finsys) that each have a stable, recognisable
 * page layout AND extract cleanly through the deterministic grid
 * extractor. When fingerprinted we can map columns to roles from a
 * per-ERP header→role table and skip the wizard — same playbook as
 * `perBankRules.ts` does for HDFC / ICICI / Canara.
 *
 * Mirrors `perBankRules.ts`. If grid extraction worked but no rule
 * fingerprint matches, OR a required role is missing after mapping,
 * we return null — the caller falls back to the interactive wizard.
 *
 * The four formats we currently support, with their distinguishing
 * tells:
 *
 *   Busy        — single-letter "B" voucher-type column (J / C / P),
 *                 "Totals C/F" / "Totals B/F" carry-forward markers,
 *                 dd-mm-yyyy dates. All-caps account-name section
 *                 headers between transaction blocks.
 *
 *   Marg ERP    — dd.mm.yyyy dates (the dotted format is almost
 *                 unique to Marg in the Indian ERP market), "Balance
 *                 c/f:" / "Balance b/f:" with lowercase + colon,
 *                 "Page X of Y" pagination, account names with a
 *                 leading dash ("-HDFC BANK LTD.").
 *
 *   Tally       — month-abbrev + day dates ("Apr 1", "Jun 30") with
 *                 the year only on the first row, "Carried Over" /
 *                 "Continued..N" page-rollover markers, amounts
 *                 without Indian comma grouping.
 *
 *   Finsys ERP  — "Generated By Finsys ERP" page footer, "Ledger
 *                 Code :" banner, "Totals & Balance" subtotal label.
 *                 Each transaction occupies two visual rows: row 1
 *                 has the date in the date column, row 2 has the
 *                 voucher number (which fails parseDate). The
 *                 existing applyMapping continuation-merge handles
 *                 the row-2 join automatically — the row-2 narration
 *                 / amount cells get appended to the row-1 transaction.
 */

import { inferFiscalYearStart, parseDate, type ColumnMapping, type ColumnRole, type PdfGrid } from './pdfGrid';

interface ErpRule {
  /** Display name surfaced in the success toast and console logs. */
  name: string;
  /** Lowercase substrings searched for in the joined text of the
   *  first ~100 grid rows. Any match counts as a positive
   *  fingerprint hit. We scan further than the bank rule (30 rows)
   *  because dense ledger pages (40+ transactions) push page-footer
   *  markers like "Generated By Finsys" / "Carried Over" past the
   *  first 30 rows. */
  fingerprints: string[];
  /** Header → role table. Iterated in order for each grid column;
   *  first matching pattern wins. List specific patterns first. */
  headerRules: Array<{ pattern: RegExp; role: ColumnRole }>;
  /** Roles that MUST be present after mapping for the rule to fire.
   *  Missing any one means grid extraction didn't surface the full
   *  table — bail and fall back to the wizard. */
  required: ColumnRole[];
}

const MARG: ErpRule = {
  name: 'Marg ERP',
  fingerprints: [
    // Lowercase "balance c/f:" with the colon is Marg-specific. Busy
    // uses "Totals C/F" (capitalised, no colon). Tally uses "Carried
    // Over". So matching this substring uniquely picks Marg.
    'balance c/f:',
    'balance b/f:',
  ],
  headerRules: [
    { pattern: /balance/i, role: 'balance' },
    { pattern: /debit/i, role: 'debit' },
    { pattern: /credit/i, role: 'credit' },
    { pattern: /narration|particulars|description/i, role: 'narration' },
    { pattern: /^date/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

const BUSY: ErpRule = {
  name: 'Busy',
  fingerprints: [
    // "Totals C/F" / "Totals B/F" appear at every page boundary in
    // Busy ledgers and don't show up in any of the other ERPs.
    'totals c/f',
    'totals b/f',
  ],
  headerRules: [
    // The single-letter "B" column (between Date and Narration) is
    // Busy's voucher-type code (J = Journal, C = Cash, P = Payment).
    // Header is literally "B".
    { pattern: /^b$/i, role: 'voucher' },
    { pattern: /balance/i, role: 'balance' },
    { pattern: /debit/i, role: 'debit' },
    { pattern: /credit/i, role: 'credit' },
    { pattern: /narration|particulars/i, role: 'narration' },
    { pattern: /^date/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

const TALLY: ErpRule = {
  name: 'Tally',
  fingerprints: [
    // Page footer + inter-page marker. "Continued..N" with the
    // double dot is a Tally idiom; "Carried Over" is the page-bottom
    // total label.
    'carried over',
    'continued..',
  ],
  headerRules: [
    { pattern: /balance/i, role: 'balance' },
    { pattern: /debit/i, role: 'debit' },
    { pattern: /credit/i, role: 'credit' },
    { pattern: /particulars|narration/i, role: 'narration' },
    { pattern: /^date/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

const FINSYS: ErpRule = {
  name: 'Finsys ERP',
  fingerprints: [
    // Page-footer signature — the only place "finsys" appears in the
    // PDF. Survives even when the banner is cropped on a re-export.
    'generated by finsys erp',
    // Banner labels — "Ledger Code :" with the space before the
    // colon is Finsys's house style; "Totals & Balance" is the
    // page-bottom subtotal row. Either alone is enough on its own.
    'ledger code :',
    'totals & balance',
  ],
  headerRules: [
    // Finsys voucher column is literally "Type" — single word, often
    // a single character ('J', 'P', 'R') in data cells. Anchor on
    // the exact header to avoid catching "Account Type" in narration.
    { pattern: /^type$/i, role: 'voucher' },
    { pattern: /balance/i, role: 'balance' },
    // Header is usually "Debit Amount" / "Credit Amount" but some
    // exports trim to just "Debit" / "Credit". Match either.
    { pattern: /debit(?:\s*amount)?/i, role: 'debit' },
    { pattern: /credit(?:\s*amount)?/i, role: 'credit' },
    { pattern: /particulars|narration|description/i, role: 'narration' },
    // "Date" is usually alone but the extractor sometimes joins it
    // with the adjacent "Vch.No." header into "Date Vch.No." — accept
    // either. The continuation-merge in applyMapping handles the
    // row-2 voucher-number rows (which fail parseDate) by appending
    // them to the previous transaction.
    { pattern: /^date(?:\s+vch)?$|^date$|vch\.?\s*no/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

// All four ERP fingerprints are mutually exclusive — Marg's "balance
// c/f:" (lowercase + colon), Busy's "totals c/f", Tally's
// "carried over" / "continued..", and Finsys's "generated by finsys
// erp" / "ledger code :" don't overlap. FINSYS is listed before
// TALLY because Finsys exports occasionally include a "Statement of
// Account" banner that could superficially resemble Tally — checking
// the Finsys-specific tells first avoids a false-positive Tally hit.
const RULES: ErpRule[] = [MARG, BUSY, FINSYS, TALLY];

export interface DetectedErpMapping {
  erp: string;
  mapping: ColumnMapping;
}

/**
 * Match the grid against the known-ERP rule set. Returns the
 * deterministic mapping when a rule fires AND every required role is
 * covered. Returns null otherwise so the caller falls through to the
 * wizard.
 *
 * The first rule whose fingerprint hits is the only one tried —
 * fingerprints are mutually exclusive in practice. If headers turn
 * out incomplete we don't try a different rule.
 */
export function detectAndMapLedgerErp(grid: PdfGrid | null): DetectedErpMapping | null {
  if (!grid) return null;
  if (grid.rows.length < 5) return null;
  // Marg has 5 cols (no voucher), the others have 5-7. Anything
  // below 5 means the extractor merged columns and the wizard would
  // be the safer path anyway.
  if (grid.columnCount < 5) return null;

  const fingerprint = grid.rows.slice(0, 100).flat().join(' ').toLowerCase();
  const rule = RULES.find(r => r.fingerprints.some(fp => fingerprint.includes(fp)));
  if (!rule) return null;

  const roles: ColumnRole[] = new Array(grid.columnCount).fill('skip');
  const headers = grid.columnHeaders ?? [];
  const taken = new Set<ColumnRole>();
  for (let c = 0; c < grid.columnCount; c++) {
    const header = (headers[c] ?? '').trim();
    if (!header) continue;
    const match = rule.headerRules.find(r => r.pattern.test(header));
    if (!match) continue;
    // First-wins for unique roles. 'skip' is allowed to repeat
    // (multiple skip-able columns is common — Type + S.No. + etc).
    if (match.role !== 'skip' && taken.has(match.role)) continue;
    roles[c] = match.role;
    if (match.role !== 'skip') taken.add(match.role);
  }

  for (const r of rule.required) {
    if (!roles.includes(r)) {
      console.warn(
        `[perLedgerErpRules] ${rule.name} fingerprint matched but required role "${r}" missing. Headers: ${headers.map(h => `"${h ?? ''}"`).join(', ')}. Falling back to wizard.`,
      );
      return null;
    }
  }

  // Header-column → data-column shift correction. Some Busy ledger
  // PDFs split each numeric column in two: a left-aligned header
  // text column ("Debit" / "Credit" / "Balance") and a right-
  // aligned data column for the actual numbers. The header→role
  // mapping anchors the role on the header column, but the data
  // lives one column to the right with an empty header. For each
  // numeric role, if the assigned column is empty for most dated
  // rows but the next column is rich with numbers AND currently
  // mapped to 'skip', shift the role over by one. Catches the
  // "credit/debit/balance one column behind" extractor symptom
  // without requiring the user to fix it manually.
  const dateColForShift = roles.indexOf('date');
  if (dateColForShift >= 0) {
    const defaultYearForShift = inferFiscalYearStart(grid.rows) ?? undefined;
    const datedRows = grid.rows
      .slice(1)
      .filter(r => parseDate((r[dateColForShift] ?? '').trim(), defaultYearForShift))
      .slice(0, 10);
    if (datedRows.length >= 3) {
      const numAt = (i: number) => datedRows.filter(r => /\d/.test((r[i] ?? '').trim())).length;
      for (const numericRole of ['debit', 'credit', 'amount', 'balance'] as const) {
        const col = roles.indexOf(numericRole);
        if (col < 0 || col >= roles.length - 1) continue;
        if (roles[col + 1] !== 'skip') continue;
        const cur = numAt(col);
        const next = numAt(col + 1);
        if (cur < datedRows.length / 4 && next >= Math.ceil(datedRows.length / 2)) {
          console.log(`[perLedgerErpRules] ${rule.name} shifting ${numericRole} from col ${col} → col ${col + 1} (${cur}/${datedRows.length} numeric vs ${next}/${datedRows.length} in next column)`);
          roles[col] = 'skip';
          roles[col + 1] = numericRole;
        }
      }
    }
  }

  // Trust-but-verify: confirm the columns the rule mapped actually
  // contain the kind of data the role expects. The grid extractor
  // sometimes merges adjacent columns when one is narrow / sparse,
  // producing cells whose header says one thing but whose contents
  // are something else. Two checks worth running:
  //
  //   1. The 'date' column should yield parseable dates for most
  //      rows whose date cell is non-empty. If the extractor merged
  //      an S.No. column in (cells become "1 09/04/2025"), parseDate
  //      will fail and applyMapping silently drops every txn.
  //
  //   2. The 'narration' column should have non-trivial text for
  //      most rows that have a date. If the extractor merged
  //      narration INTO the date column instead (Finsys-style
  //      stacked-cell layouts: date+particulars in one column,
  //      narration column empty), this catches it. Without this
  //      check the rule fires, applyMapping produces transactions
  //      with empty narrations, and the audit can't classify them.
  //
  // Sample only rows where the date column has text — ledger PDFs
  // are full of header / continuation / totals rows with empty
  // date columns that would drag the parse-rate down for benign
  // reasons. Tally compact dates ("Apr 1") need a defaultYear —
  // pull it from the period header via inferFiscalYearStart.
  const dateCol = roles.indexOf('date');
  const narrationCol = roles.indexOf('narration');
  if (dateCol >= 0) {
    const defaultYear = inferFiscalYearStart(grid.rows) ?? undefined;
    const samples = grid.rows
      .slice(1)
      .filter(r => (r[dateCol] ?? '').trim() !== '')
      .slice(0, 10);
    if (samples.length > 0) {
      const dateHits = samples.filter(r => parseDate((r[dateCol] ?? '').trim(), defaultYear)).length;
      if (dateHits < Math.max(2, Math.ceil(samples.length / 2))) {
        console.warn(
          `[perLedgerErpRules] ${rule.name} fingerprint + headers matched but column ${dateCol} ("${headers[dateCol] ?? ''}") only had ${dateHits}/${samples.length} parseable date rows — likely a merged column. Falling back to wizard.`,
        );
        return null;
      }
      if (narrationCol >= 0) {
        // 5 chars is the floor — Busy's TF / BT / RTGS narrations
        // are short but always at least 2-3 chars; we want to
        // catch the "narration column completely empty" failure
        // mode without false-flagging short legitimate narrations.
        const narrationHits = samples.filter(r => (r[narrationCol] ?? '').trim().length >= 3).length;
        if (narrationHits < Math.max(2, Math.ceil(samples.length / 2))) {
          console.warn(
            `[perLedgerErpRules] ${rule.name} fingerprint + headers matched but column ${narrationCol} ("${headers[narrationCol] ?? ''}") was empty in ${samples.length - narrationHits}/${samples.length} dated rows — narration likely merged into another column. Falling back to wizard.`,
          );
          return null;
        }
      }
    }
  }

  return { erp: rule.name, mapping: { roles } };
}
