/**
 * Per-ERP deterministic column rules for ledger PDFs.
 *
 * Ledger exports come from a small number of accounting packages
 * (Tally, Busy, Marg, Finsys) that each have a stable, recognisable
 * page layout. When the grid extractor surfaces text cleanly we can
 * fingerprint the source ERP from a few signature substrings in the
 * page banner / footer / column headers, then map the columns to
 * roles deterministically — skipping the column-mapping wizard the
 * way the bank-statement pipeline does for HDFC / ICICI / Canara.
 *
 * Mirrors `perBankRules.ts`. If grid extraction worked but no rule
 * fingerprint matches, OR a required role is missing after mapping,
 * we return null — the caller falls back to the interactive wizard.
 *
 * The four formats we currently support, with their distinguishing
 * tells:
 *
 *   Busy        — single-letter "B" voucher-type column (J / C / P),
 *                 "Totals C/F" / "Totals B/F" carry-forward markers,
 *                 dd-mm-yyyy dates. All-caps account-name section
 *                 headers between transaction blocks.
 *
 *   Marg ERP    — dd.mm.yyyy dates (the dotted format is almost
 *                 unique to Marg in the Indian ERP market), "Balance
 *                 c/f:" / "Balance b/f:" with lowercase + colon,
 *                 "Page X of Y" pagination, account names with a
 *                 leading dash ("-HDFC BANK LTD.").
 *
 *   Tally       — month-abbrev + day dates ("Apr 1", "Jun 30") with
 *                 the year only on the first row, "Carried Over" /
 *                 "Continued..N" page-rollover markers, amounts
 *                 without Indian comma grouping.
 *
 *   Finsys ERP  — mimics Tally cosmetically (uses "SUNDRY DEBTORS")
 *                 but is given away by the "Generated By Finsys ERP
 *                 Web" page footer. Has a `Type` column with
 *                 numeric voucher codes — SALE(40), RECE(11),
 *                 JOB(41), GST(58), CRED(32) — that we treat as
 *                 'skip' since they're not recoverable as standard
 *                 voucher types.
 */

import type { ColumnMapping, ColumnRole, PdfGrid } from './pdfGrid';

interface ErpRule {
  /** Display name surfaced in the success toast and console logs. */
  name: string;
  /** Lowercase substrings searched for in the joined text of the
   *  first ~100 grid rows. Any match counts as a positive
   *  fingerprint hit. We scan further than the bank rule (30 rows)
   *  because dense ledger pages (40+ transactions) push page-footer
   *  markers like "Generated By Finsys" / "Carried Over" past the
   *  first 30 rows. */
  fingerprints: string[];
  /** Header → role table. Iterated in order for each grid column;
   *  first matching pattern wins. List specific patterns first. */
  headerRules: Array<{ pattern: RegExp; role: ColumnRole }>;
  /** Roles that MUST be present after mapping for the rule to fire.
   *  Missing any one means grid extraction didn't surface the full
   *  table — bail and fall back to the wizard. */
  required: ColumnRole[];
}

const FINSYS: ErpRule = {
  name: 'Finsys ERP',
  fingerprints: [
    'generated by finsys erp',  // page footer — dead giveaway
    'ledger code :',             // banner field
    'totals & balance',          // page-rollover terminology
  ],
  headerRules: [
    { pattern: /vch\.?\s*no/i, role: 'voucher' },
    // The Type column carries codes like SALE(40)/RECE(11) that aren't
    // useful as a standard voucher type — treat as skip.
    { pattern: /^type$/i, role: 'skip' },
    { pattern: /balance/i, role: 'balance' },
    { pattern: /debit(?:\s*amount)?/i, role: 'debit' },
    { pattern: /credit(?:\s*amount)?/i, role: 'credit' },
    { pattern: /particulars|narration|description/i, role: 'narration' },
    // Finsys often stacks "Date" and "Vch.No." in the same column —
    // header text may come through as "Date Vch.No." or split.
    { pattern: /^date(?:\s+vch)?$|^date$/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

const MARG: ErpRule = {
  name: 'Marg ERP',
  fingerprints: [
    // Lowercase "balance c/f:" with the colon is Marg-specific. Busy
    // uses "Totals C/F" (capitalised, no colon). Tally uses "Carried
    // Over". So matching this substring uniquely picks Marg.
    'balance c/f:',
    'balance b/f:',
  ],
  headerRules: [
    { pattern: /balance/i, role: 'balance' },
    { pattern: /debit/i, role: 'debit' },
    { pattern: /credit/i, role: 'credit' },
    { pattern: /narration|particulars|description/i, role: 'narration' },
    { pattern: /^date/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

const BUSY: ErpRule = {
  name: 'Busy',
  fingerprints: [
    // "Totals C/F" / "Totals B/F" appear at every page boundary in
    // Busy ledgers and don't show up in any of the other ERPs.
    'totals c/f',
    'totals b/f',
  ],
  headerRules: [
    // The single-letter "B" column (between Date and Narration) is
    // Busy's voucher-type code (J = Journal, C = Cash, P = Payment).
    // Header is literally "B".
    { pattern: /^b$/i, role: 'voucher' },
    { pattern: /balance/i, role: 'balance' },
    { pattern: /debit/i, role: 'debit' },
    { pattern: /credit/i, role: 'credit' },
    { pattern: /narration|particulars/i, role: 'narration' },
    { pattern: /^date/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

const TALLY: ErpRule = {
  name: 'Tally',
  fingerprints: [
    // Page footer + inter-page marker. "Continued..N" with the
    // double dot is a Tally idiom; "Carried Over" is the page-bottom
    // total label.
    'carried over',
    'continued..',
  ],
  headerRules: [
    { pattern: /balance/i, role: 'balance' },
    { pattern: /debit/i, role: 'debit' },
    { pattern: /credit/i, role: 'credit' },
    { pattern: /particulars|narration/i, role: 'narration' },
    { pattern: /^date/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

// Ordering matters: Finsys before Tally because Finsys mimics Tally
// cosmetically (uses "SUNDRY DEBTORS" / "Statement of Account") and
// would otherwise pass-through. Marg / Busy fingerprints are mutually
// exclusive with the rest.
const RULES: ErpRule[] = [FINSYS, MARG, BUSY, TALLY];

export interface DetectedErpMapping {
  erp: string;
  mapping: ColumnMapping;
}

/**
 * Match the grid against the known-ERP rule set. Returns the
 * deterministic mapping when a rule fires AND every required role is
 * covered. Returns null otherwise so the caller falls through to the
 * wizard.
 *
 * The first rule whose fingerprint hits is the only one tried —
 * fingerprints are mutually exclusive in practice. If headers turn
 * out incomplete we don't try a different rule.
 */
export function detectAndMapLedgerErp(grid: PdfGrid | null): DetectedErpMapping | null {
  if (!grid) return null;
  if (grid.rows.length < 5) return null;
  // Marg has 5 cols (no voucher), the others have 5-7. Anything
  // below 5 means the extractor merged columns and the wizard would
  // be the safer path anyway.
  if (grid.columnCount < 5) return null;

  const fingerprint = grid.rows.slice(0, 100).flat().join(' ').toLowerCase();
  const rule = RULES.find(r => r.fingerprints.some(fp => fingerprint.includes(fp)));
  if (!rule) return null;

  const roles: ColumnRole[] = new Array(grid.columnCount).fill('skip');
  const headers = grid.columnHeaders ?? [];
  const taken = new Set<ColumnRole>();
  for (let c = 0; c < grid.columnCount; c++) {
    const header = (headers[c] ?? '').trim();
    if (!header) continue;
    const match = rule.headerRules.find(r => r.pattern.test(header));
    if (!match) continue;
    // First-wins for unique roles. 'skip' is allowed to repeat
    // (multiple skip-able columns is common — Type + S.No. + etc).
    if (match.role !== 'skip' && taken.has(match.role)) continue;
    roles[c] = match.role;
    if (match.role !== 'skip') taken.add(match.role);
  }

  for (const r of rule.required) {
    if (!roles.includes(r)) {
      console.warn(
        `[perLedgerErpRules] ${rule.name} fingerprint matched but required role "${r}" missing. Headers: ${headers.map(h => `"${h ?? ''}"`).join(', ')}. Falling back to wizard.`,
      );
      return null;
    }
  }

  return { erp: rule.name, mapping: { roles } };
}
