/**
 * Per-ERP deterministic column rules for ledger PDFs.
 *
 * Ledger exports come from a small number of accounting packages
 * (Tally, Busy, Marg, Finsys) that each have a stable, recognisable
 * page layout AND extract cleanly through the deterministic grid
 * extractor. When fingerprinted we can map columns to roles from a
 * per-ERP header→role table and skip the wizard — same playbook as
 * `perBankRules.ts` does for HDFC / ICICI / Canara.
 *
 * Mirrors `perBankRules.ts`. If grid extraction worked but no rule
 * fingerprint matches, OR a required role is missing after mapping,
 * we return null — the caller falls back to the interactive wizard.
 *
 * The four formats we currently support, with their distinguishing
 * tells:
 *
 *   Busy        — single-letter "B" voucher-type column (J / C / P),
 *                 "Totals C/F" / "Totals B/F" carry-forward markers,
 *                 dd-mm-yyyy dates. All-caps account-name section
 *                 headers between transaction blocks.
 *
 *   Marg ERP    — dd.mm.yyyy dates (the dotted format is almost
 *                 unique to Marg in the Indian ERP market), "Balance
 *                 c/f:" / "Balance b/f:" with lowercase + colon,
 *                 "Page X of Y" pagination, account names with a
 *                 leading dash ("-HDFC BANK LTD.").
 *
 *   Tally       — month-abbrev + day dates ("Apr 1", "Jun 30") with
 *                 the year only on the first row, "Carried Over" /
 *                 "Continued..N" page-rollover markers, amounts
 *                 without Indian comma grouping.
 *
 *   Finsys ERP  — "Generated By Finsys ERP" page footer, "Ledger
 *                 Code :" banner, "Totals & Balance" subtotal label.
 *                 Each transaction occupies two visual rows: row 1
 *                 has the date in the date column, row 2 has the
 *                 voucher number (which fails parseDate). The
 *                 existing applyMapping continuation-merge handles
 *                 the row-2 join automatically — the row-2 narration
 *                 / amount cells get appended to the row-1 transaction.
 */

import { inferFiscalYearStart, parseDate, type ColumnMapping, type ColumnRole, type PdfGrid } from './pdfGrid';

interface ErpRule {
  /** Display name surfaced in the success toast and console logs. */
  name: string;
  /** Lowercase substrings searched for in the joined text of the
   *  first ~100 grid rows. Any match counts as a positive
   *  fingerprint hit. We scan further than the bank rule (30 rows)
   *  because dense ledger pages (40+ transactions) push page-footer
   *  markers like "Generated By Finsys" / "Carried Over" past the
   *  first 30 rows. */
  fingerprints: string[];
  /** Optional grid-reshape hook. Runs AFTER the fingerprint matches
   *  but BEFORE headerRules / required checks. Use this when an ERP's
   *  compact PDF layout merges two logical columns into one grid
   *  cell — Tally's "Vch No. Debit" merged header (Hotel Holiday Inn
   *  2024-25 export) is the canonical case: the Vch No and the Debit
   *  amount land in the same column as bareint, "<bareint> <currency>",
   *  or "<currency> Dr/Cr" cells depending on row type. Mirrors
   *  `preprocess` in perBankRules.ts; return a new PdfGrid with the
   *  split applied or the input grid unchanged to skip. */
  preprocess?: (grid: PdfGrid) => PdfGrid;
  /** Header → role table. Iterated in order for each grid column;
   *  first matching pattern wins. List specific patterns first. */
  headerRules: Array<{ pattern: RegExp; role: ColumnRole }>;
  /** Roles that MUST be present after mapping for the rule to fire.
   *  Missing any one means grid extraction didn't surface the full
   *  table — bail and fall back to the wizard. */
  required: ColumnRole[];
}

const MARG: ErpRule = {
  name: 'Marg ERP',
  fingerprints: [
    // Lowercase "balance c/f:" with the colon is Marg-specific. Busy
    // uses "Totals C/F" (capitalised, no colon). Tally uses "Carried
    // Over". So matching this substring uniquely picks Marg.
    'balance c/f:',
    'balance b/f:',
  ],
  headerRules: [
    { pattern: /balance/i, role: 'balance' },
    { pattern: /debit/i, role: 'debit' },
    { pattern: /credit/i, role: 'credit' },
    { pattern: /narration|particulars|description/i, role: 'narration' },
    { pattern: /^date/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

const BUSY: ErpRule = {
  name: 'Busy',
  fingerprints: [
    // "Totals C/F" / "Totals B/F" appear at every page boundary in
    // Busy ledgers and don't show up in any of the other ERPs.
    'totals c/f',
    'totals b/f',
  ],
  headerRules: [
    // The single-letter "B" column (between Date and Narration) is
    // Busy's voucher-type code (J = Journal, C = Cash, P = Payment).
    // Header is literally "B".
    { pattern: /^b$/i, role: 'voucher' },
    { pattern: /balance/i, role: 'balance' },
    { pattern: /debit/i, role: 'debit' },
    { pattern: /credit/i, role: 'credit' },
    { pattern: /narration|particulars/i, role: 'narration' },
    { pattern: /^date/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

// Tally's compact multi-column ledger layout (Hotel Holiday Inn
// 2024-25 single-account-per-page export is the canonical case)
// merges the "Vch No." and "Debit" header cells into one anchor —
// the two headers print on adjacent x-positions with less gap than
// the extractor's column-merge threshold, so the actual row-5 header
// reads "Vch No. Debit" in a single cell and the data column below
// holds whichever value is present for the row:
//
//   "By" voucher rows (credit-side, no debit):     "60"
//   "To" voucher rows (debit-side with amount):    "2841 538.00"
//   Pure debit rows (opening balance, page total): "5,57,432.00"
//   Contra-detail child rows (no Vch No):          "92,000.00 Dr"
//   Header row:                                    "Vch No. Debit"
//   Banner / blank rows:                           ""
//
// Without this preprocess the rule has to either drop 'debit' from
// `required` (losing wizard validation — the wizard refuses any
// mapping that has neither a Debit+Credit pair nor a single Amount
// column) or demote the column to 'reference' (losing the actual
// debit amounts on every "To" row). Both compromises produce wrong
// transaction extraction.
//
// The split logic walks every row and:
//   - bareint only ("60")          → left = "60",  right = ""
//   - bareint + currency ("2841 538.00")    → left = "2841", right = "538.00"
//   - pure currency ("5,57,432.00")         → left = "",     right = "5,57,432.00"
//     (opening-balance / page-total rows where the Vch No slot is
//     blank — the amount is a debit-side total, goes right)
//   - currency + Dr/Cr ("92,000.00 Dr")     → left = "",     right = "92,000.00 Dr"
//     (preserves the suffix so the contra-detail guard in
//     applyMapping recognises it)
//   - anything else (header row, banner)    → left = original, right = ""
//
// Candidate-column detection: scan first 50 rows; pick the column
// where ≥60% of non-empty cells match the split patterns AND ≥1
// cell has the merged "<bareint> <currency>" form (the latter is
// the smoking gun — a plain "Vch No." column without merging never
// produces that shape, and a plain "Debit" column without merging
// never has bareint cells). Only one column qualifies in practice.
//
// If no column qualifies the function returns the grid unchanged
// (non-merged Tally exports with separate Vch No / Debit columns
// flow through normally).
function tallySplitMergedVchNoDebit(grid: PdfGrid): PdfGrid {
  // Cells where the only content is a Vch No, optionally followed by
  // a currency-shape amount (decimal-required so a leading-Vch-No
  // narration like "2841 Cheque payment" doesn't match).
  const vchNoMaybeAmount = /^(\d+)(?:\s+([\d,]+\.\d+))?$/;
  // Pure currency cells (Indian comma grouping, mandatory decimal).
  const pureCurrency = /^[\d,]+\.\d+$/;
  // Contra-detail amount cells: currency-shape followed by Dr/Cr
  // suffix. "92,000.00 Dr", "16,560.00Cr", etc.
  const drCrAmount = /^[\d,]+\.\d+\s*(?:dr|cr)\.?$/i;
  const matchesSplit = (s: string): boolean =>
    vchNoMaybeAmount.test(s) || pureCurrency.test(s) || drCrAmount.test(s);

  const sample = grid.rows.slice(0, 50);
  let splitCol = -1;
  for (let c = 0; c < grid.columnCount; c++) {
    let nonEmpty = 0;
    let matches = 0;
    let merged = 0;
    for (const r of sample) {
      const v = (r[c] ?? '').trim();
      if (!v) continue;
      nonEmpty++;
      if (matchesSplit(v)) matches++;
      const m = vchNoMaybeAmount.exec(v);
      if (m && m[2]) merged++;
    }
    // Need ≥5 non-empty cells, ≥60% conformance, AND ≥1 merged cell.
    // Threshold is 60% (not higher) because the column also picks up
    // header repeats ("Vch No. Debit") on every page break — three
    // header rows in a 15-cell sample knocks the ratio down without
    // proving the column isn't merged.
    if (nonEmpty >= 5 && matches >= nonEmpty * 0.6 && merged >= 1) {
      splitCol = c;
      break;
    }
  }
  if (splitCol < 0) return grid;

  console.log(`[perLedgerErpRules] Tally splitting merged Vch No./Debit column at index ${splitCol}`);

  const newColumnCount = grid.columnCount + 1;
  const newRows: string[][] = grid.rows.map(r => {
    const out: string[] = new Array(newColumnCount).fill('');
    for (let i = 0; i < splitCol; i++) out[i] = r[i] ?? '';
    const cell = (r[splitCol] ?? '').trim();
    const vMatch = vchNoMaybeAmount.exec(cell);
    if (vMatch) {
      out[splitCol] = vMatch[1];                  // Vch No
      out[splitCol + 1] = vMatch[2] ?? '';        // Debit amount (if merged)
    } else if (pureCurrency.test(cell) || drCrAmount.test(cell)) {
      out[splitCol] = '';                          // No Vch No
      out[splitCol + 1] = cell;                    // → debit column (preserves Dr/Cr suffix for contra-detail guard)
    } else {
      // Header row, banner, or unrecognised — keep content in left
      // column so it doesn't pollute the new debit column. Headers
      // are overridden below regardless.
      out[splitCol] = cell;
      out[splitCol + 1] = '';
    }
    for (let i = splitCol + 1; i < grid.columnCount; i++) {
      out[i + 1] = r[i] ?? '';
    }
    return out;
  });

  const oldHeaders = grid.columnHeaders ?? [];
  const newHeaders: Array<string | null> = new Array(newColumnCount).fill('');
  for (let i = 0; i < splitCol; i++) newHeaders[i] = oldHeaders[i] ?? '';
  // Force canonical header names — the original merged header was
  // some variant of "Vch No. Debit" and we want headerRules to match
  // /^(?:vch\.?\s*)?no\.?\b/ on the left and /^debit/ on the right.
  newHeaders[splitCol] = 'Vch No.';
  newHeaders[splitCol + 1] = 'Debit';
  for (let i = splitCol + 1; i < oldHeaders.length; i++) {
    newHeaders[i + 1] = oldHeaders[i] ?? '';
  }

  return {
    ...grid,
    rows: newRows,
    columnCount: newColumnCount,
    columnHeaders: newHeaders,
  };
}

// Tally "Detailed Ledger" / "Daily Activity Sheet" exports surface
// Particulars and Narration as TWO separate columns instead of the
// compact layout that fuses them. Particulars holds the contra-
// account label ("By ASSA ABLOY..." / "To HDFC BANK(2735)"),
// Narration holds the long description with bill references and
// bank refs ("NEFT DR-SCBL0036046-...-BILL 25001376"). The cross-
// party bill matcher reads the narration field to pull the BILL
// number — without the Narration column we lose every customer-side
// payment's reconciliation key.
//
// headerRules's /particulars|narration/i pattern is column-iterated
// left-to-right with first-wins, so Particulars (the earlier column)
// claims 'narration' and Narration falls through to skip — silently
// dropping the BILL refs. ASSA ABLOY's Interio Paradise reconciliation
// is the canonical case: the customer-side Tally book has both
// columns and matching against the supplier's Dynamics AX books was
// returning zero matches.
//
// Fix: when BOTH "Particulars" AND "Narration" exist as distinct
// headers, append the Narration cell's content to the Particulars
// cell, clear the Narration cell. The narration field then carries
// both pieces and extractBillKey downstream sees the BILL token.
//
// Gate: requires both headers as exact matches. Standard Tally
// exports with "Particulars" alone (Hotel Holiday Inn style) flow
// through untouched — the find for "^narration$" returns -1 and the
// function is a no-op.
function tallyMergeParticularsNarration(grid: PdfGrid): PdfGrid {
  const headers = grid.columnHeaders ?? [];
  const partIdx = headers.findIndex(h => h && /^particulars$/i.test(h.trim()));
  const narrIdx = headers.findIndex(h => h && /^narration$/i.test(h.trim()));
  if (partIdx < 0 || narrIdx < 0 || partIdx === narrIdx) return grid;
  // Type column is the third source — Tally's Detailed Ledger PDFs
  // sometimes overflow narration into the Type column when the
  // narration line is long enough to cross x-position clusters
  // (ASSA ABLOY's NEFT references hit this on every payment row —
  // the cell ends up "ABLOY OPENING SOLUTIONS INDIA PVT-NETBANK,
  // MUM-HDFCN5202...-BILL 25001376 Payment", with the actual Vch
  // Type "Payment" as the suffix). When detected (cell ends with a
  // Vch Type token but isn't ONLY the token), the prefix is appended
  // to the narration so the BILL <num> token survives into
  // extractBillKey downstream. Pure-VchType cells ("Payment" /
  // "Journal" alone) flow through untouched.
  const typeIdx = headers.findIndex(h => h && /^(?:vch\.?\s*)?type$/i.test(h.trim()));
  // Known Vch Type vocabulary. Anchored as suffix so we don't strip
  // a "Payment" embedded in mid-narration text.
  const VCH_TYPE_PURE = /^\s*(?:Payment|Journal|Purchase|Receipt|Contra|Sales|Debit\s*Note|Credit\s*Note|Sale|Rcpt|Pymt)\s*$/i;
  const VCH_TYPE_SUFFIX = /\s(Payment|Journal|Purchase|Receipt|Contra|Sales|Debit\s*Note|Credit\s*Note|Sale|Rcpt|Pymt)\s*$/i;

  console.log(`[perLedgerErpRules] Tally consolidating narration: Particulars (col ${partIdx}) ← Narration (col ${narrIdx})${typeIdx >= 0 ? ` ← Type (col ${typeIdx}, overflow prefix only)` : ''}`);

  const newRows = grid.rows.map(r => {
    const out = [...r];
    const p = (r[partIdx] ?? '').trim();
    const n = (r[narrIdx] ?? '').trim();
    let merged = p && n ? `${p} ${n}` : (n || p);
    if (typeIdx >= 0) {
      const t = (r[typeIdx] ?? '').trim();
      // Only treat Type as narration-overflow when (a) it isn't a
      // bare Vch Type token AND (b) it ends with one — i.e. the
      // "<narration> <VchType>" shape. We append everything BEFORE
      // the trailing Vch Type to the narration; the Type cell stays
      // as-is so the voucher role still picks up the trailing token
      // (the existing 'voucher' mapping is content-tolerant — bill
      // matching reads narration first, so a noisy voucher is
      // harmless here).
      if (t && !VCH_TYPE_PURE.test(t)) {
        const suffix = VCH_TYPE_SUFFIX.exec(t);
        if (suffix && suffix.index > 0) {
          const prefix = t.slice(0, suffix.index).trim();
          if (prefix) {
            merged = merged ? `${merged} ${prefix}` : prefix;
          }
          // Replace the Type cell with JUST the Vch Type token so
          // the downstream voucher mapping carries "Payment" /
          // "Journal" / "Purchase" instead of the long overflow
          // narration. Without this clean-up, voucher cells like
          // "ABLOY OPENING SOLUTIONS INDIA PVT-NETBANK, MUM-HDFCN5
          // 2025...-BILL PAYMENT Payment" feed extractBillKey's
          // voucher fallback (when narration has "BILL PAYMENT"
          // shorthand and no real bill number) and produce 75-char
          // synthetic bill keys that bucket-collide every payment.
          out[typeIdx] = (suffix[1] ?? '').trim();
        }
      }
    }
    if (merged) {
      out[partIdx] = merged;
      out[narrIdx] = '';
    }
    return out;
  });
  return { ...grid, rows: newRows };
}

const TALLY: ErpRule = {
  name: 'Tally',
  fingerprints: [
    // Page footer + inter-page marker. "Continued..N" (double-dot)
    // is one Tally export style; "continued ..." (three dots with
    // a leading space) is the alternative Tally produces from the
    // print-to-PDF path. "Carried Over" is the page-bottom total
    // label common to both styles. Listing all three substrings so
    // either variant triggers detection.
    'carried over',
    'continued..',
    'continued ...',
    'continued...',
    // "(as per details)" is Tally's lowercase parenthetical phrase
    // for voucher entries that have a contra-account breakdown
    // listed below them — appears on the parent row of every
    // multi-leg journal. Unique to Tally (Marg uses "as per
    // details", Busy doesn't use the phrase, Finsys doesn't either).
    // Appears on page 1 of the export so this matches early even
    // when "carried over" lives past the row-window.
    '(as per details)',
    // The "Vch Type" / "Vch No." column headers are a Tally idiom —
    // Marg uses "Type / V.No.", Busy uses just a single "B" column,
    // Finsys uses "Type" alone. Substring match.
    'vch type',
    'vch no.',
  ],
  // Two preprocess stages chained:
  //   1. tallyMergeParticularsNarration — fold a separate "Narration"
  //      column INTO the Particulars column when both exist (Detailed
  //      Ledger / Daily Activity exports). No-op for the compact
  //      single-Particulars layout.
  //   2. tallySplitMergedVchNoDebit — split the merged "Vch No. Debit"
  //      column into two when the extractor fused them (compact
  //      single-account-per-page Hotel Holiday Inn export). No-op for
  //      already-separate Vch No / Debit columns.
  // Both stages are content-only / column-count-stable for the wide
  // export, so they compose safely in either order; we run the
  // Particulars merge first since it's the simpler op (no column-
  // insertion bookkeeping).
  preprocess: grid => tallySplitMergedVchNoDebit(tallyMergeParticularsNarration(grid)),
  // headerRules: 'reference' is listed BEFORE 'debit' so that on
  // unmerged Tally exports (with a plain "Vch No." header) the Vch
  // No column gets 'reference' first and isn't grabbed by /^debit/.
  // After the preprocess split runs on merged-layout exports the
  // two synthetic headers are exactly "Vch No." and "Debit" so the
  // first match for each is unambiguous.
  headerRules: [
    { pattern: /balance/i, role: 'balance' },
    { pattern: /^(?:vch\.?\s*)?no\.?\b/i, role: 'reference' },
    { pattern: /^(?:vch\.?\s*)?type\b|voucher\s*type/i, role: 'voucher' },
    { pattern: /^debit/i, role: 'debit' },
    { pattern: /^credit/i, role: 'credit' },
    { pattern: /particulars|narration/i, role: 'narration' },
    { pattern: /^date/i, role: 'date' },
  ],
  // Balance is INTENTIONALLY not required. Two Tally export shapes
  // surface in practice:
  //   - Compact "Ledger Account" (Hotel Holiday Inn) — has a Balance
  //     column. balance role gets assigned via headerRules; the
  //     closing-balance pickup in mappedRowsToExtractedLedger uses it.
  //   - Detailed Ledger / Daily Activity (ASSA ABLOY Interio
  //     Paradise) — debit + credit + running balance live in the
  //     Credit column only (Tally writes the running balance below
  //     the credit number on the same row). No standalone Balance
  //     column. Earlier the rule vetoed this layout — falling back
  //     to the wizard which hit two further problems (Narration
  //     column dropped to skip via first-wins, Vch No. Debit merged
  //     cell mis-read as debit=voucher-number).
  // applyMapping treats balance as nullable: the debit/credit-derived
  // signed amount path is unaffected; only the running-balance delta
  // fallback (a recovery for misclustered amount cells) doesn't fire.
  // Net: removing balance from required lets this rule fire on
  // balance-less exports with NO loss on balanced exports.
  required: ['date', 'narration', 'debit', 'credit'],
};

// Finsys's wider exports (Statement of Account / Customer ledger
// variant — OSPL Future Energy is the canonical case) collapse the
// "Date | Vch.No. | Particulars" header trio into a single column at
// extraction time. Each transaction line lands in col 0 as
// "DD/MM/YYYY <narration>" with the Particulars column (col 1) empty
// across every data row. The trust-but-verify narration check then
// rejects the rule because col 1 looks unmapped, and the file falls
// through to the wizard — losing the deterministic extraction we
// already know how to do.
//
// Split col 0 on the leading "DD/MM/YYYY " prefix: keep the date in
// col 0, push the rest into col 1 (which is empty anyway). Voucher
// continuation rows in the same export carry "<vch-no> <bill-detail>"
// in col 0 — those get their col-0 cleared so the row is treated as
// a date-less continuation, and the bill detail goes into the
// narration column for continuation-merge to fold in.
//
// Gate: only fire when col 0 looks like a merged date+narration
// column AND col 1 is mostly empty. Two checks so this is a no-op on
// already-clean Finsys exports where Particulars sits in its own
// column.
function finsysSplitDateNarrationColumn(grid: PdfGrid): PdfGrid {
  const datePrefix = /^(\d{1,2}\/\d{1,2}\/\d{2,4})\s+(.+)$/;
  const vchPrefix = /^(\d{4,8})\s+(.+)$/;
  const sample = grid.rows.slice(0, 80);
  const dateMatches = sample.filter(r => datePrefix.test((r[0] ?? '').trim())).length;
  if (dateMatches < 5) return grid;
  // If col 1 has its own content, the export is already separated.
  // Don't risk overwriting genuine narration data.
  const col1Populated = sample.filter(r => (r[1] ?? '').trim().length > 0).length;
  if (col1Populated > 5) return grid;

  console.log(`[perLedgerErpRules] Finsys ERP splitting merged Date+Narration column 0 (${dateMatches}/${sample.length} rows have date prefix, col 1 empty in ${sample.length - col1Populated}/${sample.length})`);

  // "Balance B/f" is the per-page opening-balance carry-forward
  // Finsys prints at the top of every page. The first occurrence
  // (page 1) is the account's actual opening balance; subsequent
  // ones are visual page-break repeats. Both land with col 0 =
  // "Balance B/f" and col 1 empty, so the downstream opening
  // detection (which keys on `narration === "Opening Balance"`)
  // misses them entirely — opening reads as 0 and recon math is
  // off by the carry-forward value. Rewrite col 0 / col 1 so the
  // first row's narration matches the opening regex; later
  // occurrences contribute amount=0 placeholders (harmless to
  // totals — see opening-balance rescue in flushPending).
  const balanceBf = /^balance\s+b\s*\/?\s*f\b/i;
  const newRows: string[][] = grid.rows.map(r => {
    const out = [...r];
    while (out.length < grid.columnCount) out.push('');
    const cell0 = (r[0] ?? '').trim();
    const dateMatch = datePrefix.exec(cell0);
    if (dateMatch) {
      out[0] = dateMatch[1];
      out[1] = dateMatch[2];
      return out;
    }
    const vchMatch = vchPrefix.exec(cell0);
    if (vchMatch) {
      // Continuation row: vch no + bill-detail text. Clear col 0 so
      // parseDate fails (correct — this row has no date), put the
      // bill-detail in col 1 so the continuation-merge in
      // applyMapping folds it into the parent transaction's narration.
      out[0] = '';
      out[1] = vchMatch[2];
      return out;
    }
    if (balanceBf.test(cell0)) {
      // Translate to the canonical "Opening Balance" narration so
      // the downstream opening pickup matches it. Clear col 0 so
      // parseDate fails (it's not a transaction date).
      out[0] = '';
      out[1] = 'Opening Balance';
      return out;
    }
    return out;
  });
  return { ...grid, rows: newRows };
}

const FINSYS: ErpRule = {
  name: 'Finsys ERP',
  fingerprints: [
    // Page-footer signature — the only place "finsys" appears in the
    // PDF. Survives even when the banner is cropped on a re-export.
    'generated by finsys erp',
    // Banner labels — "Ledger Code :" with the space before the
    // colon is Finsys's house style; "Totals & Balance" is the
    // page-bottom subtotal row. Either alone is enough on its own.
    'ledger code :',
    'totals & balance',
  ],
  preprocess: finsysSplitDateNarrationColumn,
  headerRules: [
    // Finsys voucher column is literally "Type" — single word, often
    // a single character ('J', 'P', 'R') in data cells. Anchor on
    // the exact header to avoid catching "Account Type" in narration.
    { pattern: /^type$/i, role: 'voucher' },
    { pattern: /balance/i, role: 'balance' },
    // Header is usually "Debit Amount" / "Credit Amount" but some
    // exports trim to just "Debit" / "Credit". Match either.
    { pattern: /debit(?:\s*amount)?/i, role: 'debit' },
    { pattern: /credit(?:\s*amount)?/i, role: 'credit' },
    { pattern: /particulars|narration|description/i, role: 'narration' },
    // "Date" is usually alone but the extractor sometimes joins it
    // with the adjacent "Vch.No." header into "Date Vch.No." — accept
    // either. The continuation-merge in applyMapping handles the
    // row-2 voucher-number rows (which fail parseDate) by appending
    // them to the previous transaction.
    { pattern: /^date(?:\s+vch)?$|^date$|vch\.?\s*no/i, role: 'date' },
  ],
  required: ['date', 'narration', 'debit', 'credit', 'balance'],
};

// Microsoft Dynamics AX / D365 F&O "Customer - internal account
// statement" report. ASSA ABLOY Opening Solutions India is the
// canonical case — the export lists every transaction posted to a
// customer's AR account over a fiscal period, with the invoice's
// billing classification, due date, and per-invoice remainder.
//
// Layout (fixed 7-column grid the extractor yields):
//   col 0: Date         — transaction date in US locale M/D/YYYY
//   col 1: Voucher      — "AA-" prefix optionally followed by the
//                          journal voucher number ("GINJA25002044" /
//                          "GIN25004485"). On the continuation row
//                          the customer voucher (IIV / SRE / FJV /
//                          ICV / CRN) appears alone.
//   col 2: Description  — billing classification ("IN5IN250417011LT")
//                          OR free-text ("Opening", "R OFF",
//                          "1I0032 Q1- 2025", "OCT'25"). Often
//                          empty when col 1 carries the journal #.
//   col 3: type         — Bank document type. Almost always literal
//                          "None"; pure noise.
//   col 4: Amount       — single signed amount with the due date
//                          and currency code appended inline:
//                          "124,688.00 5/23/2025 INR" or
//                          "-200,000.00 4/17/2025 INR". parseNumber
//                          locks onto the first numeric token so the
//                          trailing date+currency is harmless.
//   col 5: (no header)  — "Amount in transaction currency" — the
//                          clean signed amount without the inline
//                          due date. We don't use it (col 4 already
//                          gives us the same value via parseNumber)
//                          and its header is null so headerRules
//                          can't bind to it anyway.
//   col 6: (no header)  — "Remainder currency" — per-invoice unpaid
//                          balance after FIFO payment matching.
//                          Not a running balance, so not mapped.
//
// Two-rows-per-transaction layout: each customer transaction occupies
// row N (date + AA- prefix + amount) plus row N+1 (the matched
// customer voucher, date-less). applyMapping's continuation-merge
// folds row N+1 into row N's narration automatically — no rule-side
// preprocess needed for that.
//
// Distinguishing tells (mutually exclusive with the existing four
// ERPs — none of "customer - internal account statement", "billing
// classification", or "amount in transaction" appears in Marg / Busy
// / Tally / Finsys exports):
//   - "Customer - internal account statement" page banner — Dynamics
//     AX is the only ERP producing this exact phrase as the report
//     title.
//   - "Billing classification" column header — D365 F&O-specific
//     invoice-reference field.
//   - "Amount in transaction currency" column header — Dynamics AX
//     splits the amount into (Amount Due) and (Amount in transaction
//     currency); the latter phrase doesn't appear in other exports.
//
// US-locale date handling: Dynamics AX defaults to MM/DD/YYYY in
// English/US installations. parseDate's existing DD/MM/YYYY regex
// would read "4/17/2025" as dd=4, mm=17, producing the invalid ISO
// string "2025-17-04" — the row gets attributed to "month 17" and
// every downstream date sort / aggregation breaks. The
// dynamicsAxNormalizeDates preprocess detects MM/DD layout from
// sample dates (any cell whose middle group exceeds 12 forces the
// US reading) and swaps mm/dd in col 0 so parseDate sees a clean
// DD/MM/YYYY string. Conservative gate: needs ≥2 unambiguous M/D
// cells (mm > 12 evidence) — exports already configured to use
// DD/MM under an Indian locale fall through untouched.
function dynamicsAxNormalizeDates(grid: PdfGrid): PdfGrid {
  // Column 0 is always the date column in this format — the report
  // layout is fixed. We don't search for the date column the way
  // the per-bank rules do because the headerRules step hasn't run
  // yet at preprocess time.
  const DATE_COL = 0;
  const mdyExact = /^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/;
  const sample = grid.rows.slice(0, 80);
  let mdyEvidence = 0;
  for (const r of sample) {
    const m = mdyExact.exec((r[DATE_COL] ?? '').trim());
    if (!m) continue;
    const middle = Number(m[2]);
    // Middle group > 12 can only be DD under MM/DD/YYYY; under
    // DD/MM/YYYY it would be the month, which is invalid for >12.
    if (middle > 12) mdyEvidence++;
  }
  if (mdyEvidence < 2) return grid;  // No strong M/D evidence — leave alone.

  console.log(`[perLedgerErpRules] Dynamics AX normalising MM/DD/YYYY → DD/MM/YYYY in date column (${mdyEvidence} unambiguous MDY cells in first ${sample.length} rows)`);

  const newRows = grid.rows.map(r => {
    const out = [...r];
    const cell = (r[DATE_COL] ?? '').trim();
    const m = mdyExact.exec(cell);
    if (m) {
      // Swap month and day positions. parseDate will then read this
      // as DD/MM/YYYY and emit the correct ISO string.
      out[DATE_COL] = `${m[2]}/${m[1]}/${m[3]}`;
    }
    return out;
  });
  return { ...grid, rows: newRows };
}

const DYNAMICS_AX: ErpRule = {
  name: 'Microsoft Dynamics AX',
  fingerprints: [
    // Page-banner title — appears on every page. Nothing else in the
    // Indian ERP market uses this exact phrase.
    'customer - internal account statement',
    // Column-header tells from the report's multi-line header. The
    // grid extractor flattens multi-row headers so these come through
    // as substrings of the joined first-page text.
    'billing classification',
    'amount in transaction',
  ],
  preprocess: dynamicsAxNormalizeDates,
  headerRules: [
    // "Description" → narration. Anchored so "Bank document type"
    // (col 3 header is the bare word "type") doesn't accidentally
    // collapse into this match.
    { pattern: /^description$|^particulars|^billing\s*classification/i, role: 'narration' },
    // "Voucher" — the AA- prefix + journal voucher number column.
    // Header is the bare word "Voucher" (col 1) after the grid
    // extractor strips the multi-line continuation "Invoice".
    { pattern: /^voucher\b/i, role: 'voucher' },
    // "Amount" alone OR "Amount Due". The cell carries the amount
    // plus the due date and currency code as trailing tokens
    // ("124,688.00 5/23/2025 INR"); parseNumber grabs the first
    // numeric token so the suffix is harmless.
    { pattern: /^amount(?:\s+due)?$/i, role: 'amount' },
    // "Date" — col 0 header. Anchored so "Assessment date" or
    // metadata-row dates don't accidentally bind.
    { pattern: /^date$/i, role: 'date' },
  ],
  // Required roles: date + narration + amount is enough for the audit
  // pipeline. No debit/credit pair (single-signed amount column) and
  // no running balance (the "Remainder currency" column is a
  // per-invoice unpaid balance under FIFO matching, not a running
  // total — wrong semantics for the 'balance' role).
  required: ['date', 'narration', 'amount'],
};

// Fingerprints across all five ERPs are mutually exclusive — Marg's
// "balance c/f:" (lowercase + colon), Busy's "totals c/f", Tally's
// "carried over" / "continued..", Finsys's "generated by finsys erp"
// / "ledger code :", and Dynamics AX's "customer - internal account
// statement" don't overlap. FINSYS is listed before TALLY because
// Finsys exports occasionally include a "Statement of Account"
// banner that could superficially resemble Tally; DYNAMICS_AX is
// listed before TALLY for the same defensive reason ("Customer -
// internal account statement" contains the substring "account
// statement" which Tally exports also use in their banner).
const RULES: ErpRule[] = [MARG, BUSY, FINSYS, DYNAMICS_AX, TALLY];

export interface DetectedErpMapping {
  erp: string;
  mapping: ColumnMapping;
  /** The grid the mapping is indexed against. Equal to the input grid
   *  when the rule has no preprocess hook (Marg / Busy / Finsys all
   *  flow through unchanged). When the TALLY rule preprocesses a
   *  merged "Vch No. Debit" column the grid here is the POST-split
   *  version — column count and cell contents differ from what
   *  extractPdfGrid returned. The mapping's role array indexes align
   *  with THIS grid, not the input.
   *
   *  Callers that show the user a preview (column-mapping wizard) or
   *  call applyMapping MUST use this grid — feeding the original grid
   *  with a preprocessed mapping produces an off-by-one render. */
  grid: PdfGrid;
}

/**
 * Match the grid against the known-ERP rule set. Returns the
 * deterministic mapping when a rule fires AND every required role is
 * covered. Returns null otherwise so the caller falls through to the
 * wizard.
 *
 * The first rule whose fingerprint hits is the only one tried —
 * fingerprints are mutually exclusive in practice. If headers turn
 * out incomplete we don't try a different rule.
 */
export function detectAndMapLedgerErp(gridIn: PdfGrid | null): DetectedErpMapping | null {
  if (!gridIn) return null;
  if (gridIn.rows.length < 5) return null;
  // Marg has 5 cols (no voucher), the others have 5-7. Anything
  // below 5 means the extractor merged columns and the wizard would
  // be the safer path anyway.
  if (gridIn.columnCount < 5) return null;

  // Scan a generous window — 200 rows. Bumped from 100 because Tally's
  // single-account-per-page exports (Hotel Holiday Inn style — one
  // account per PDF page, ~20 rows each) push the page-bottom
  // "Carried Over" marker past row 100 when the first few accounts
  // are short. Still cheap (string concatenation over a few thousand
  // chars). The whole-document fallback is implicit — if 200 rows
  // doesn't cover it, the explicit Tally-specific tells we added
  // ("(as per details)", "vch type", "vch no.") catch the early
  // rows on page 1.
  const fingerprint = gridIn.rows.slice(0, 200).flat().join(' ').toLowerCase();
  const rule = RULES.find(r => r.fingerprints.some(fp => fingerprint.includes(fp)));
  if (!rule) return null;

  // Run the per-ERP preprocess hook (if any) BEFORE header → role
  // assignment. Lets a rule reshape the grid — e.g. Tally splits a
  // merged "Vch No. Debit" cell into two columns — so the downstream
  // headerRules / required check sees the corrected layout. The
  // returned mapping is indexed against this preprocessed grid (see
  // DetectedErpMapping.grid).
  let grid = gridIn;
  if (rule.preprocess) {
    try {
      grid = rule.preprocess(gridIn);
    } catch (err) {
      console.warn(`[perLedgerErpRules] ${rule.name} preprocess threw, falling back to raw grid: ${(err as Error).message}`);
      grid = gridIn;
    }
  }

  const roles: ColumnRole[] = new Array(grid.columnCount).fill('skip');
  const headers = grid.columnHeaders ?? [];
  const taken = new Set<ColumnRole>();
  for (let c = 0; c < grid.columnCount; c++) {
    const header = (headers[c] ?? '').trim();
    if (!header) continue;
    const match = rule.headerRules.find(r => r.pattern.test(header));
    if (!match) continue;
    // First-wins for unique roles. 'skip' is allowed to repeat
    // (multiple skip-able columns is common — Type + S.No. + etc).
    if (match.role !== 'skip' && taken.has(match.role)) continue;
    roles[c] = match.role;
    if (match.role !== 'skip') taken.add(match.role);
  }

  for (const r of rule.required) {
    if (!roles.includes(r)) {
      console.warn(
        `[perLedgerErpRules] ${rule.name} fingerprint matched but required role "${r}" missing. Headers: ${headers.map(h => `"${h ?? ''}"`).join(', ')}. Falling back to wizard.`,
      );
      return null;
    }
  }

  // Header-column → data-column shift correction. Some Busy ledger
  // PDFs split each numeric column in two: a left-aligned header
  // text column ("Debit" / "Credit" / "Balance") and a right-
  // aligned data column for the actual numbers. The header→role
  // mapping anchors the role on the header column, but the data
  // lives one column to the right with an empty header. For each
  // numeric role, if the assigned column is empty for most dated
  // rows but the next column is rich with numbers AND currently
  // mapped to 'skip', shift the role over by one. Catches the
  // "credit/debit/balance one column behind" extractor symptom
  // without requiring the user to fix it manually.
  const dateColForShift = roles.indexOf('date');
  if (dateColForShift >= 0) {
    const defaultYearForShift = inferFiscalYearStart(grid.rows) ?? undefined;
    // Sample 50 dated rows (was 10) — single-direction streaks in the
    // first batch (e.g. an all-debit opening month on a credit account)
    // produced incorrect non-shifts on the smaller sample. 50 rows
    // almost always contains both directions on a typical account; the
    // few that don't get rescued by the companion-shift pass below.
    const datedRows = grid.rows
      .slice(1)
      .filter(r => parseDate((r[dateColForShift] ?? '').trim(), defaultYearForShift))
      .slice(0, 50);
    if (datedRows.length >= 3) {
      // Any-digit and currency-shape counters. Currency-shape means
      // the cell contains a decimal point or an Indian comma group
      // ("1,08,560.00" or "538.00" — both qualify). Bare integers
      // ("60", "2840") have digits but no currency shape; those are
      // typically Vch No fields the grid extractor mis-aligned into
      // the Debit column anchor on Tally exports where the "Vch Type"
      // header tokenized into two anchors and shifted everything to
      // its right by one. The Hotel Holiday Inn Tally PDF (2026-05)
      // surfaces this exactly: 100% of dated rows had a number in
      // col 5 (every Vch No), defeating the "col is mostly empty"
      // shift heuristic. Currency-shape pins it.
      const numAt = (i: number) => datedRows.filter(r => /\d/.test((r[i] ?? '').trim())).length;
      const currencyAt = (i: number) => datedRows.filter(r => {
        const s = (r[i] ?? '').trim();
        return /\d/.test(s) && /[.,]/.test(s);
      }).length;
      let anyNumericShift = false;
      for (const numericRole of ['debit', 'credit', 'amount', 'balance'] as const) {
        const col = roles.indexOf(numericRole);
        if (col < 0 || col >= roles.length - 1) continue;
        if (roles[col + 1] !== 'skip') continue;
        const cur = numAt(col);
        const next = numAt(col + 1);
        const curCurrency = currencyAt(col);
        const nextCurrency = currencyAt(col + 1);
        // Case A (original) — col is mostly empty, next is mostly numeric.
        const emptyAndFull = cur < datedRows.length / 4 && next >= Math.ceil(datedRows.length / 2);
        // Case B (new) — col is full of BARE-INTEGER numbers (no
        // decimals/commas) while next is full of CURRENCY-SHAPE
        // numbers. Pins the Tally header-shift case.
        const integerThenCurrency =
          cur >= Math.ceil(datedRows.length / 2) &&
          curCurrency < datedRows.length / 4 &&
          nextCurrency >= Math.ceil(datedRows.length / 2);
        if (emptyAndFull || integerThenCurrency) {
          console.log(`[perLedgerErpRules] ${rule.name} shifting ${numericRole} from col ${col} → col ${col + 1} (${cur}/${datedRows.length} numeric, ${curCurrency} currency-shape vs ${next}/${datedRows.length} numeric, ${nextCurrency} currency-shape in next column)`);
          roles[col] = 'skip';
          roles[col + 1] = numericRole;
          anyNumericShift = true;
        }
      }
      // Companion-shift: if any numeric role just shifted, the layout
      // is a confirmed header-text / data-column split. For any other
      // numeric role whose current column has 0 numeric data AND the
      // next column is 'skip' with an empty header (signature of the
      // split layout), shift on faith even without per-column numeric
      // evidence. Catches the streak case where a single-direction
      // ledger period leaves the opposing-sign column with no data
      // in the sample, so the direct-shift pass can't fire on it.
      if (anyNumericShift) {
        for (const numericRole of ['debit', 'credit', 'amount'] as const) {
          const col = roles.indexOf(numericRole);
          if (col < 0 || col >= roles.length - 1) continue;
          if (roles[col + 1] !== 'skip') continue;
          if (numAt(col) > 0) continue;
          const nextHeader = (headers[col + 1] ?? '').trim();
          if (nextHeader !== '') continue;
          console.log(`[perLedgerErpRules] ${rule.name} companion-shifting ${numericRole} from col ${col} → col ${col + 1} (sibling shift confirmed split-header layout; no data evidence in sampled rows but next col is unmapped + headerless)`);
          roles[col] = 'skip';
          roles[col + 1] = numericRole;
        }
      }

      // Same empty→full shift for NON-numeric roles (voucher,
      // reference, account). The Tally "Hotel Holiday Inn 2024-25"
      // PDF surfaces this with the voucher column: columnHeaders
      // placed "Type" at col 3, but actual "Purchase" / "Journal"
      // values sit at col 4. Without this pass the wizard preview
      // shows "Voucher / Type" mapped to an empty column while the
      // real Vch Type data sits in a "Skip" column next to it.
      // Symmetric to the numeric pass above — only fires when col
      // is empty and col+1 has text.
      const nonEmptyAt = (i: number) => datedRows.filter(r => (r[i] ?? '').trim().length > 0).length;
      for (const nonNumericRole of ['voucher', 'reference', 'account'] as const) {
        const col = roles.indexOf(nonNumericRole);
        if (col < 0 || col >= roles.length - 1) continue;
        if (roles[col + 1] !== 'skip') continue;
        const cur = nonEmptyAt(col);
        const next = nonEmptyAt(col + 1);
        if (cur < datedRows.length / 4 && next >= Math.ceil(datedRows.length / 2)) {
          console.log(`[perLedgerErpRules] ${rule.name} shifting ${nonNumericRole} from col ${col} → col ${col + 1} (${cur}/${datedRows.length} populated vs ${next}/${datedRows.length} in next column)`);
          roles[col] = 'skip';
          roles[col + 1] = nonNumericRole;
        }
      }
    }
  }

  // Trust-but-verify: confirm the columns the rule mapped actually
  // contain the kind of data the role expects. The grid extractor
  // sometimes merges adjacent columns when one is narrow / sparse,
  // producing cells whose header says one thing but whose contents
  // are something else. Two checks worth running:
  //
  //   1. The 'date' column should yield parseable dates for most
  //      rows whose date cell is non-empty. If the extractor merged
  //      an S.No. column in (cells become "1 09/04/2025"), parseDate
  //      will fail and applyMapping silently drops every txn.
  //
  //   2. The 'narration' column should have non-trivial text for
  //      most rows that have a date. If the extractor merged
  //      narration INTO the date column instead (Finsys-style
  //      stacked-cell layouts: date+particulars in one column,
  //      narration column empty), this catches it. Without this
  //      check the rule fires, applyMapping produces transactions
  //      with empty narrations, and the audit can't classify them.
  //
  // Pre-filter samples to "date-shaped" candidates (substring matches
  // /\d{1,4}[\/.\-]\d{1,2}[\/.\-]\d{1,4}/ for numeric dates, or a
  // 3-letter month for Tally's "Apr 1" / "Jun 30" compact form).
  // Without that filter, multi-account ledgers that repeat a banner
  // on every page (Tally's "Statement of Account", Busy's section
  // headers) drown the first 10 non-empty col-0 cells in banner text,
  // every parseDate call returns null, and the rule self-vetoes on a
  // perfectly valid file. Banner-only rows lack date shape; real
  // transaction rows always have one — so this filter cleanly
  // separates them. Same fix is applied in perBankRules.ts.
  const dateCol = roles.indexOf('date');
  const narrationCol = roles.indexOf('narration');
  if (dateCol >= 0) {
    const defaultYear = inferFiscalYearStart(grid.rows) ?? undefined;
    const dateLike = /\d{1,4}[\/.\-]\d{1,2}[\/.\-]\d{1,4}|\b(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\b/i;
    const samples = grid.rows
      .slice(1)
      .filter(r => dateLike.test((r[dateCol] ?? '').trim()))
      .slice(0, 20);
    if (samples.length === 0) {
      console.warn(
        `[perLedgerErpRules] ${rule.name} fingerprint + headers matched but column ${dateCol} ("${headers[dateCol] ?? ''}") had no date-shaped values. Falling back to wizard.`,
      );
      return null;
    }
    {
      const dateHits = samples.filter(r => parseDate((r[dateCol] ?? '').trim(), defaultYear)).length;
      if (dateHits < Math.max(2, Math.ceil(samples.length / 2))) {
        console.warn(
          `[perLedgerErpRules] ${rule.name} fingerprint + headers matched but column ${dateCol} ("${headers[dateCol] ?? ''}") only had ${dateHits}/${samples.length} parseable date rows — likely a merged column. Falling back to wizard.`,
        );
        return null;
      }
      if (narrationCol >= 0) {
        // 5 chars is the floor — Busy's TF / BT / RTGS narrations
        // are short but always at least 2-3 chars; we want to
        // catch the "narration column completely empty" failure
        // mode without false-flagging short legitimate narrations.
        const narrationHits = samples.filter(r => (r[narrationCol] ?? '').trim().length >= 3).length;
        if (narrationHits < Math.max(2, Math.ceil(samples.length / 2))) {
          console.warn(
            `[perLedgerErpRules] ${rule.name} fingerprint + headers matched but column ${narrationCol} ("${headers[narrationCol] ?? ''}") was empty in ${samples.length - narrationHits}/${samples.length} dated rows — narration likely merged into another column. Falling back to wizard.`,
          );
          return null;
        }
      }
    }
  }

  return { erp: rule.name, mapping: { roles }, grid };
}
