/**
 * Client-side PDF rendering for the ITR wizard "preview" output.
 *
 * This is a clean Smart AI report, NOT a replica of the CBDT form layout.
 * Decision from .planning/sessions/ITR-FILING-FEATURE-PLAN.md §10.8.
 */
import { jsPDF } from 'jspdf';
import type { ItrWizardDraft } from './uiModel';
import { computeDerivedTotals } from './toCbdtJson';

function inr(n: number | undefined): string {
  return '₹' + (Number(n) || 0).toLocaleString('en-IN');
}

function title(doc: jsPDF, text: string, y: number): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(13, 150, 104);
  doc.text(text.toUpperCase(), 14, y);
  doc.setDrawColor(13, 150, 104);
  doc.line(14, y + 1, 196, y + 1);
  doc.setTextColor(0, 0, 0);
  return y + 5;
}

function row(doc: jsPDF, label: string, value: string, y: number): number {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(label, 14, y);
  doc.setFont('helvetica', 'bold');
  doc.text(value, 196, y, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  return y + 5;
}

export async function renderItrPdf(draftInput: ItrWizardDraft): Promise<void> {
  const draft = computeDerivedTotals(draftInput);
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(`${draft.formType} — Draft Return`, 14, 20);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`AY ${draft.assessmentYear} · Preview only · Generated by Smart AI`, 14, 26);
  doc.setTextColor(0, 0, 0);

  let y = 36;

  // Personal info
  y = title(doc, 'Personal info', y);
  const p = draft.PersonalInfo ?? {};
  const fullName = [p.AssesseeName?.FirstName, p.AssesseeName?.MiddleName, p.AssesseeName?.SurNameOrOrgName]
    .filter(Boolean)
    .join(' ');
  y = row(doc, 'Name', fullName || '—', y);
  y = row(doc, 'PAN', p.PAN ?? '—', y);
  y = row(doc, 'Aadhaar', p.AadhaarCardNo ?? '—', y);
  y = row(doc, 'Date of birth', p.DOB ?? '—', y);
  y = row(doc, 'Employer category', p.EmployerCategory ?? '—', y);
  const addr = p.Address ?? {};
  const addrLine = [
    addr.ResidenceNo,
    addr.ResidenceName,
    addr.RoadOrStreet,
    addr.LocalityOrArea,
    addr.CityOrTownOrDistrict,
    addr.PinCode ? String(addr.PinCode) : null,
  ]
    .filter(Boolean)
    .join(', ');
  y = row(doc, 'Address', addrLine || '—', y);
  y = row(doc, 'Mobile', addr.MobileNo ? `${addr.CountryCodeMobile ?? '91'} ${addr.MobileNo}` : '—', y);
  y = row(doc, 'Email', addr.EmailAddress ?? '—', y);
  y += 4;

  // Filing status
  y = title(doc, 'Filing status', y);
  const fs = draft.FilingStatus ?? {};
  y = row(doc, 'Section filed under', String(fs.ReturnFileSec ?? '—'), y);
  y = row(doc, 'Regime', fs.OptOutNewTaxRegime === 'N' ? 'New (default)' : 'Old', y);
  y = row(doc, 'Filing due date', fs.ItrFilingDueDate ?? '—', y);
  y += 4;

  // Income breakdown
  y = title(doc, 'Income', y);
  const inc = draft.ITR1_IncomeDeductions ?? {};
  y = row(doc, 'Gross salary', inr(inc.GrossSalary), y);
  y = row(doc, 'Less: Standard deduction', inr(inc.DeductionUs16), y);
  y = row(doc, 'Income from salary', inr(inc.IncomeFromSal), y);
  y = row(doc, 'House property', inr(inc.TotalIncomeOfHP), y);
  y = row(doc, 'Other sources', inr(inc.IncomeOthSrc), y);
  if ((draft.LTCG112A?.LongCap112A ?? 0) > 0) {
    y = row(doc, 'LTCG u/s 112A', inr(draft.LTCG112A?.LongCap112A), y);
  }
  y = row(doc, 'Gross total income', inr(inc.GrossTotIncome), y);
  y = row(doc, 'Chapter VI-A deductions', inr(inc.UsrDeductUndChapVIA?.TotalChapVIADeductions), y);
  doc.setFont('helvetica', 'bold');
  y = row(doc, 'Total taxable income', inr(inc.TotalIncome), y);
  doc.setFont('helvetica', 'normal');
  y += 4;

  // Taxes paid
  y = title(doc, 'Taxes paid', y);
  const taxes = draft.TaxPaid?.TaxesPaid ?? {};
  y = row(doc, 'Advance tax', inr(taxes.AdvanceTax), y);
  y = row(doc, 'TDS', inr(taxes.TDS), y);
  y = row(doc, 'TCS', inr(taxes.TCS), y);
  y = row(doc, 'Self-assessment tax', inr(taxes.SelfAssessmentTax), y);
  doc.setFont('helvetica', 'bold');
  y = row(doc, 'Total taxes paid', inr(taxes.TotalTaxesPaid), y);
  doc.setFont('helvetica', 'normal');
  y += 4;

  // Banks
  const banks = draft.Refund?.BankAccountDtls?.AddtnlBankDetails ?? [];
  if (banks.length > 0) {
    y = title(doc, 'Bank accounts', y);
    for (const b of banks) {
      const line = `${b.BankName ?? '—'} · ${b.IFSCCode ?? '—'} · ${b.BankAccountNo ?? '—'} · ${b.AccountType ?? 'SB'}${b.UseForRefund === 'true' ? ' (refund)' : ''}`;
      y = row(doc, '', line, y);
    }
    y += 4;
  }

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(
    'This is a draft preview. Import the downloaded JSON into the gov Common Utility and re-validate before uploading to incometax.gov.in.',
    14,
    285,
    { maxWidth: 182 },
  );

  const pan = draft.PersonalInfo?.PAN ?? 'draft';
  doc.save(`${draft.formType}_${draft.assessmentYear}_${pan}_preview.pdf`);
}
