import { useState } from 'react';
import { CreditCard } from 'lucide-react';
import jsPDF from 'jspdf';

const PAYMENT_TYPES = [
  { code: '100', label: '(100) Advance Tax' },
  { code: '300', label: '(300) Self-Assessment Tax' },
  { code: '400', label: '(400) Tax on Regular Assessment' },
  { code: '106', label: '(106) Tax on Distributed Profits' },
  { code: '102', label: '(102) Surcharge' },
];

const AY_OPTIONS = ['2026-27', '2025-26', '2024-25', '2023-24'];

function numberToWords(n: number): string {
  if (n === 0) return 'Zero';
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
    'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  function convert(num: number): string {
    if (num < 20) return ones[num];
    if (num < 100) return tens[Math.floor(num / 10)] + (num % 10 ? ' ' + ones[num % 10] : '');
    if (num < 1000) return ones[Math.floor(num / 100)] + ' Hundred' + (num % 100 ? ' and ' + convert(num % 100) : '');
    if (num < 100000) return convert(Math.floor(num / 1000)) + ' Thousand' + (num % 1000 ? ' ' + convert(num % 1000) : '');
    if (num < 10000000) return convert(Math.floor(num / 100000)) + ' Lakh' + (num % 100000 ? ' ' + convert(num % 100000) : '');
    return convert(Math.floor(num / 10000000)) + ' Crore' + (num % 10000000 ? ' ' + convert(num % 10000000) : '');
  }
  return convert(Math.round(n)) + ' Only';
}

export function Challan280Tab() {
  const [form, setForm] = useState({
    pan: '',
    name: '',
    address: '',
    phone: '',
    email: '',
    ay: '2025-26',
    paymentType: '300',
    incomeTax: '',
    surcharge: '',
    cess: '',
  });

  const patch = (p: Partial<typeof form>) => setForm((prev) => ({ ...prev, ...p }));

  const tax = Number(form.incomeTax) || 0;
  const sur = Number(form.surcharge) || 0;
  const cess = Number(form.cess) || 0;
  const total = tax + sur + cess;

  const canGenerate = form.pan.trim().length === 10 && form.name.trim().length > 0 && total > 0;

  const handleGenerate = () => {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pw = doc.internal.pageSize.getWidth();
    const margin = 15;
    let y = 20;

    // Header
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('CHALLAN NO. ITNS 280', pw / 2, y, { align: 'center' });
    y += 6;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('Tax Applicable: (0021) Income Tax (Other than Companies)', pw / 2, y, { align: 'center' });
    y += 10;

    doc.setLineWidth(0.5);
    doc.line(margin, y, pw - margin, y);
    y += 8;

    const row = (label: string, value: string) => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.text(label, margin + 2, y);
      doc.setFont('helvetica', 'bold');
      doc.text(value, pw - margin - 2, y, { align: 'right' });
      y += 7;
    };

    row('PAN', form.pan.toUpperCase());
    row('Full Name', form.name);
    if (form.address) row('Address', form.address);
    if (form.phone) row('Phone', form.phone);
    if (form.email) row('Email', form.email);
    y += 3;

    doc.setLineWidth(0.2);
    doc.line(margin, y, pw - margin, y);
    y += 8;

    row('Assessment Year', form.ay);
    const ptLabel = PAYMENT_TYPES.find(p => p.code === form.paymentType)?.label ?? form.paymentType;
    row('Type of Payment', ptLabel);
    y += 3;

    doc.setLineWidth(0.2);
    doc.line(margin, y, pw - margin, y);
    y += 8;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Tax Details', margin + 2, y);
    y += 8;

    doc.setFontSize(10);
    row('Income Tax', '₹ ' + Math.round(tax).toLocaleString('en-IN'));
    row('Surcharge', '₹ ' + Math.round(sur).toLocaleString('en-IN'));
    row('Health & Education Cess', '₹ ' + Math.round(cess).toLocaleString('en-IN'));
    y += 2;
    doc.setLineWidth(0.4);
    doc.line(margin + 60, y, pw - margin, y);
    y += 7;
    doc.setFontSize(12);
    row('TOTAL', '₹ ' + Math.round(total).toLocaleString('en-IN'));
    y += 2;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Amount in words: Rupees ${numberToWords(total)}`, margin + 2, y);
    y += 15;

    // Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(130);
    doc.text(
      'This is a pre-filled challan for reference. For actual payment, use https://onlineservices.tin.egov-nsdl.com/etaxnew/tdsnontds.jsp',
      pw / 2, y, { align: 'center', maxWidth: pw - 2 * margin },
    );
    y += 10;
    doc.text('Generated by Smartbiz AI (ai.smartbizin.com)', pw / 2, y, { align: 'center' });

    doc.save(`challan-280-${form.pan}-${form.ay}.pdf`);
  };

  return (
    <div className="max-w-2xl mx-auto space-y-5">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-emerald-50 dark:bg-emerald-900/20 flex items-center justify-center">
          <CreditCard className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
        </div>
        <div>
          <h2 className="text-base font-semibold text-gray-900 dark:text-gray-100">Challan 280 Generator</h2>
          <p className="text-[11px] text-gray-500 dark:text-gray-400">Generate pre-filled income tax payment challan</p>
        </div>
      </div>

      <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-800 p-5 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-[11px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1">PAN <span className="text-red-500">*</span></label>
            <input value={form.pan} onChange={(e) => patch({ pan: e.target.value.toUpperCase() })} maxLength={10}
              className="w-full px-3 py-2 text-sm bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500/30 text-gray-900 dark:text-gray-100 font-mono tracking-wider"
              placeholder="ABCDE1234F" />
          </div>
          <div>
            <label className="block text-[11px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1">Full name <span className="text-red-500">*</span></label>
            <input value={form.name} onChange={(e) => patch({ name: e.target.value })}
              className="w-full px-3 py-2 text-sm bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500/30 text-gray-900 dark:text-gray-100" />
          </div>
          <div>
            <label className="block text-[11px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1">Assessment year</label>
            <select value={form.ay} onChange={(e) => patch({ ay: e.target.value })}
              className="w-full px-2 py-2 text-sm bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg">
              {AY_OPTIONS.map((ay) => <option key={ay} value={ay}>{ay}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-[11px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1">Payment type</label>
            <select value={form.paymentType} onChange={(e) => patch({ paymentType: e.target.value })}
              className="w-full px-2 py-2 text-sm bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg">
              {PAYMENT_TYPES.map((p) => <option key={p.code} value={p.code}>{p.label}</option>)}
            </select>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-[11px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1">Income tax</label>
            <div className="relative">
              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm">₹</span>
              <input type="number" value={form.incomeTax} onChange={(e) => patch({ incomeTax: e.target.value })}
                className="w-full pl-7 pr-3 py-2 text-sm bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500/30 text-gray-900 dark:text-gray-100" />
            </div>
          </div>
          <div>
            <label className="block text-[11px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1">Surcharge</label>
            <div className="relative">
              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm">₹</span>
              <input type="number" value={form.surcharge} onChange={(e) => patch({ surcharge: e.target.value })}
                className="w-full pl-7 pr-3 py-2 text-sm bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500/30 text-gray-900 dark:text-gray-100" />
            </div>
          </div>
          <div>
            <label className="block text-[11px] font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-1">H&E Cess</label>
            <div className="relative">
              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm">₹</span>
              <input type="number" value={form.cess} onChange={(e) => patch({ cess: e.target.value })}
                className="w-full pl-7 pr-3 py-2 text-sm bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500/30 text-gray-900 dark:text-gray-100" />
            </div>
          </div>
        </div>

        {total > 0 && (
          <div className="flex justify-between items-center pt-3 border-t border-gray-200 dark:border-gray-800">
            <span className="text-sm font-semibold text-gray-700 dark:text-gray-300">Total payable</span>
            <span className="text-lg font-bold text-emerald-600 dark:text-emerald-400">₹ {Math.round(total).toLocaleString('en-IN')}</span>
          </div>
        )}

        <button onClick={handleGenerate} disabled={!canGenerate}
          className={`w-full py-2.5 rounded-xl font-semibold text-sm transition-all flex items-center justify-center gap-2 ${
            canGenerate ? 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm' : 'bg-gray-100 dark:bg-gray-800 text-gray-400 cursor-not-allowed'
          }`}>
          <CreditCard className="w-4 h-4" />
          Generate Challan 280 PDF
        </button>
      </div>
    </div>
  );
}
