/* eslint-disable */
/**
 * Auto-generated from CBDT ITR JSON schema.
 * Do not edit manually — run `npm run itr:enums` instead.
 * Country calling codes per CBDT enum. Used in PersonalInfo.Address.CountryCode.
 */

export interface ItrEnumOption {
  code: string;
  label: string;
}

export const COUNTRIES: readonly ItrEnumOption[] = [
  { code: "93", label: "AFGHANISTAN" },
  { code: "1001", label: "ÅLAND ISLANDS" },
  { code: "355", label: "ALBANIA" },
  { code: "213", label: "ALGERIA" },
  { code: "684", label: "AMERICAN SAMOA" },
  { code: "376", label: "ANDORRA" },
  { code: "244", label: "ANGOLA" },
  { code: "1264", label: "ANGUILLA" },
  { code: "1010", label: "ANTARCTICA" },
  { code: "1268", label: "ANTIGUA AND BARBUDA" },
  { code: "54", label: "ARGENTINA" },
  { code: "374", label: "ARMENIA" },
  { code: "297", label: "ARUBA" },
  { code: "61", label: "AUSTRALIA" },
  { code: "43", label: "AUSTRIA" },
  { code: "994", label: "AZERBAIJAN" },
  { code: "1242", label: "BAHAMAS" },
  { code: "973", label: "BAHRAIN" },
  { code: "880", label: "BANGLADESH" },
  { code: "1246", label: "BARBADOS" },
  { code: "375", label: "BELARUS" },
  { code: "32", label: "BELGIUM" },
  { code: "501", label: "BELIZE" },
  { code: "229", label: "BENIN" },
  { code: "1441", label: "BERMUDA" },
  { code: "975", label: "BHUTAN" },
  { code: "591", label: "BOLIVIA (PLURINATIONAL STATE OF)" },
  { code: "1002", label: "BONAIRE, SINT EUSTATIUS AND SABA" },
  { code: "387", label: "BOSNIA AND HERZEGOVINA" },
  { code: "267", label: "BOTSWANA" },
  { code: "1003", label: "BOUVET ISLAND" },
  { code: "55", label: "BRAZIL" },
  { code: "1014", label: "BRITISH INDIAN OCEAN TERRITORY" },
  { code: "673", label: "BRUNEI DARUSSALAM" },
  { code: "359", label: "BULGARIA" },
  { code: "226", label: "BURKINA FASO" },
  { code: "257", label: "BURUNDI" },
  { code: "238", label: "CABO VERDE" },
  { code: "855", label: "CAMBODIA" },
  { code: "237", label: "CAMEROON" },
  { code: "1", label: "CANADA" },
  { code: "1345", label: "CAYMAN ISLANDS" },
  { code: "236", label: "CENTRAL AFRICAN REPUBLIC" },
  { code: "235", label: "CHAD" },
  { code: "56", label: "CHILE" },
  { code: "86", label: "CHINA" },
  { code: "9", label: "CHRISTMAS ISLAND" },
  { code: "672", label: "COCOS (KEELING) ISLANDS" },
  { code: "57", label: "COLOMBIA" },
  { code: "270", label: "COMOROS" },
  { code: "242", label: "CONGO" },
  { code: "243", label: "CONGO (DEMOCRATIC REPUBLIC OF THE)" },
  { code: "682", label: "COOK ISLANDS" },
  { code: "506", label: "COSTA RICA" },
  { code: "225", label: "CÔTE D'IVOIRE" },
  { code: "385", label: "CROATIA" },
  { code: "53", label: "CUBA" },
  { code: "1015", label: "CURAÇAO" },
  { code: "357", label: "CYPRUS" },
  { code: "420", label: "CZECHIA" },
  { code: "45", label: "DENMARK" },
  { code: "253", label: "DJIBOUTI" },
  { code: "1767", label: "DOMINICA" },
  { code: "1809", label: "DOMINICAN REPUBLIC" },
  { code: "593", label: "ECUADOR" },
  { code: "20", label: "EGYPT" },
  { code: "503", label: "EL SALVADOR" },
  { code: "240", label: "EQUATORIAL GUINEA" },
  { code: "291", label: "ERITREA" },
  { code: "372", label: "ESTONIA" },
  { code: "251", label: "ETHIOPIA" },
  { code: "500", label: "FALKLAND ISLANDS (MALVINAS)" },
  { code: "298", label: "FAROE ISLANDS" },
  { code: "679", label: "FIJI" },
  { code: "358", label: "FINLAND" },
  { code: "33", label: "FRANCE" },
  { code: "594", label: "FRENCH GUIANA" },
  { code: "689", label: "FRENCH POLYNESIA" },
  { code: "1004", label: "FRENCH SOUTHERN TERRITORIES" },
  { code: "241", label: "GABON" },
  { code: "220", label: "GAMBIA" },
  { code: "995", label: "GEORGIA" },
  { code: "49", label: "GERMANY" },
  { code: "233", label: "GHANA" },
  { code: "350", label: "GIBRALTAR" },
  { code: "30", label: "GREECE" },
  { code: "299", label: "GREENLAND" },
  { code: "1473", label: "GRENADA" },
  { code: "590", label: "GUADELOUPE" },
  { code: "1671", label: "GUAM" },
  { code: "502", label: "GUATEMALA" },
  { code: "1481", label: "GUERNSEY" },
  { code: "224", label: "GUINEA" },
  { code: "245", label: "GUINEA-BISSAU" },
  { code: "592", label: "GUYANA" },
  { code: "509", label: "HAITI" },
  { code: "1005", label: "HEARD ISLAND AND MCDONALD ISLANDS" },
  { code: "6", label: "HOLY SEE" },
  { code: "504", label: "HONDURAS" },
  { code: "852", label: "HONG KONG" },
  { code: "36", label: "HUNGARY" },
  { code: "354", label: "ICELAND" },
  { code: "91", label: "INDIA" },
  { code: "62", label: "INDONESIA" },
  { code: "98", label: "IRAN (ISLAMIC REPUBLIC OF)" },
  { code: "964", label: "IRAQ" },
  { code: "353", label: "IRELAND" },
  { code: "1624", label: "ISLE OF MAN" },
  { code: "972", label: "ISRAEL" },
  { code: "5", label: "ITALY" },
  { code: "1876", label: "JAMAICA" },
  { code: "81", label: "JAPAN" },
  { code: "1534", label: "JERSEY" },
  { code: "962", label: "JORDAN" },
  { code: "7", label: "KAZAKHSTAN" },
  { code: "254", label: "KENYA" },
  { code: "686", label: "KIRIBATI" },
  { code: "850", label: "KOREA(DEMOCRATIC PEOPLE'S REPUBLIC OF)" },
  { code: "82", label: "KOREA (REPUBLIC OF)" },
  { code: "965", label: "KUWAIT" },
  { code: "996", label: "KYRGYZSTAN" },
  { code: "856", label: "LAO PEOPLE'S DEMOCRATIC REPUBLIC" },
  { code: "371", label: "LATVIA" },
  { code: "961", label: "LEBANON" },
  { code: "266", label: "LESOTHO" },
  { code: "231", label: "LIBERIA" },
  { code: "218", label: "LIBYA" },
  { code: "423", label: "LIECHTENSTEIN" },
  { code: "370", label: "LITHUANIA" },
  { code: "352", label: "LUXEMBOURG" },
  { code: "853", label: "MACAO" },
  { code: "389", label: "MACEDONIA(THE FORMER YUGOSLAV REPUBLIC OF)" },
  { code: "261", label: "MADAGASCAR" },
  { code: "265", label: "MALAWI" },
  { code: "60", label: "MALAYSIA" },
  { code: "960", label: "MALDIVES" },
  { code: "223", label: "MALI" },
  { code: "356", label: "MALTA" },
  { code: "692", label: "MARSHALL ISLANDS" },
  { code: "596", label: "MARTINIQUE" },
  { code: "222", label: "MAURITANIA" },
  { code: "230", label: "MAURITIUS" },
  { code: "269", label: "MAYOTTE" },
  { code: "52", label: "MEXICO" },
  { code: "691", label: "MICRONESIA (FEDERATED STATES OF)" },
  { code: "373", label: "MOLDOVA (REPUBLIC OF)" },
  { code: "377", label: "MONACO" },
  { code: "976", label: "MONGOLIA" },
  { code: "382", label: "MONTENEGRO" },
  { code: "1664", label: "MONTSERRAT" },
  { code: "212", label: "MOROCCO" },
  { code: "258", label: "MOZAMBIQUE" },
  { code: "95", label: "MYANMAR" },
  { code: "264", label: "NAMIBIA" },
  { code: "674", label: "NAURU" },
  { code: "977", label: "NEPAL" },
  { code: "31", label: "NETHERLANDS" },
  { code: "687", label: "NEW CALEDONIA" },
  { code: "64", label: "NEW ZEALAND" },
  { code: "505", label: "NICARAGUA" },
  { code: "227", label: "NIGER" },
  { code: "234", label: "NIGERIA" },
  { code: "683", label: "NIUE" },
  { code: "15", label: "NORFOLK ISLAND" },
  { code: "1670", label: "NORTHERN MARIANA ISLANDS" },
  { code: "47", label: "NORWAY" },
  { code: "968", label: "OMAN" },
  { code: "92", label: "PAKISTAN" },
  { code: "680", label: "PALAU" },
  { code: "970", label: "PALESTINE, STATE OF" },
  { code: "507", label: "PANAMA" },
  { code: "675", label: "PAPUA NEW GUINEA" },
  { code: "595", label: "PARAGUAY" },
  { code: "51", label: "PERU" },
  { code: "63", label: "PHILIPPINES" },
  { code: "1011", label: "PITCAIRN" },
  { code: "48", label: "POLAND" },
  { code: "14", label: "PORTUGAL" },
  { code: "1787", label: "PUERTO RICO" },
  { code: "974", label: "QATAR" },
  { code: "262", label: "RÉUNION" },
  { code: "40", label: "ROMANIA" },
  { code: "8", label: "RUSSIAN FEDERATION" },
  { code: "250", label: "RWANDA" },
  { code: "1006", label: "SAINT BARTHÉLEMY" },
  { code: "290", label: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA" },
  { code: "1869", label: "SAINT KITTS AND NEVIS" },
  { code: "1758", label: "SAINT LUCIA" },
  { code: "1007", label: "SAINT MARTIN (FRENCH PART)" },
  { code: "508", label: "SAINT PIERRE AND MIQUELON" },
  { code: "1784", label: "SAINT VINCENT AND THE GRENADINES" },
  { code: "685", label: "SAMOA" },
  { code: "378", label: "SAN MARINO" },
  { code: "239", label: "SAO TOME AND PRINCIPE" },
  { code: "966", label: "SAUDI ARABIA" },
  { code: "221", label: "SENEGAL" },
  { code: "381", label: "SERBIA" },
  { code: "248", label: "SEYCHELLES" },
  { code: "232", label: "SIERRA LEONE" },
  { code: "65", label: "SINGAPORE" },
  { code: "1721", label: "SINT MAARTEN (DUTCH PART)" },
  { code: "421", label: "SLOVAKIA" },
  { code: "386", label: "SLOVENIA" },
  { code: "677", label: "SOLOMON ISLANDS" },
  { code: "252", label: "SOMALIA" },
  { code: "28", label: "SOUTH AFRICA" },
  { code: "1008", label: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS" },
  { code: "211", label: "SOUTH SUDAN" },
  { code: "35", label: "SPAIN" },
  { code: "94", label: "SRI LANKA" },
  { code: "249", label: "SUDAN" },
  { code: "597", label: "SURINAME" },
  { code: "1012", label: "SVALBARD AND JAN MAYEN" },
  { code: "268", label: "SWAZILAND" },
  { code: "46", label: "SWEDEN" },
  { code: "41", label: "SWITZERLAND" },
  { code: "963", label: "SYRIAN ARAB REPUBLIC" },
  { code: "886", label: "TAIWAN" },
  { code: "992", label: "TAJIKISTAN" },
  { code: "255", label: "TANZANIA, UNITED REPUBLIC OF" },
  { code: "66", label: "THAILAND" },
  { code: "670", label: "TIMOR-LESTE (EAST TIMOR)" },
  { code: "228", label: "TOGO" },
  { code: "690", label: "TOKELAU" },
  { code: "676", label: "TONGA" },
  { code: "1868", label: "TRINIDAD AND TOBAGO" },
  { code: "216", label: "TUNISIA" },
  { code: "90", label: "TURKEY" },
  { code: "993", label: "TURKMENISTAN" },
  { code: "1649", label: "TURKS AND CAICOS ISLANDS" },
  { code: "688", label: "TUVALU" },
  { code: "256", label: "UGANDA" },
  { code: "380", label: "UKRAINE" },
  { code: "971", label: "UNITED ARAB EMIRATES" },
  { code: "44", label: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND" },
  { code: "2", label: "UNITED STATES OF AMERICA" },
  { code: "1009", label: "UNITED STATES MINOR OUTLYING ISLANDS" },
  { code: "598", label: "URUGUAY" },
  { code: "998", label: "UZBEKISTAN" },
  { code: "678", label: "VANUATU" },
  { code: "58", label: "VENEZUELA (BOLIVARIAN REPUBLIC OF)" },
  { code: "84", label: "VIET NAM" },
  { code: "1284", label: "VIRGIN ISLANDS (BRITISH)" },
  { code: "1340", label: "VIRGIN ISLANDS (U.S.)" },
  { code: "681", label: "WALLIS AND FUTUNA" },
  { code: "1013", label: "WESTERN SAHARA" },
  { code: "967", label: "YEMEN" },
  { code: "260", label: "ZAMBIA" },
  { code: "263", label: "ZIMBABWE" },
  { code: "9999", label: "OTHERS" },
] as const;

export type COUNTRIESCode = typeof COUNTRIES[number]['code'];
