/* eslint-disable */
/**
 * Auto-generated from CBDT ITR JSON schema.
 * Do not edit manually — run `npm run itr:enums` instead.
 * CBDT Nature-of-Business / Profession codes for ITR-4 presumptive schemes (44AD / 44ADA / 44AE).
 */

export interface ItrEnumOption {
  code: string;
  label: string;
}

export const NATURE_OF_BUSINESS: readonly ItrEnumOption[] = [
  { code: "01001", label: "Growing and manufacturing of tea" },
  { code: "01002", label: "Growing and manufacturing of coffee" },
  { code: "01003", label: "Growing and manufacturing of rubber" },
  { code: "01004", label: "Market gardening and horticulture specialties" },
  { code: "01005", label: "Raising of silk worms and production of silk" },
  { code: "01006", label: "Raising of bees and production of honey" },
  { code: "01007", label: "Raising of poultry and production of eggs" },
  { code: "01008", label: "Rearing of sheep and production of wool" },
  { code: "01009", label: "Rearing of animals and production of animal products" },
  { code: "01010", label: "Agricultural and animal husbandry services" },
  { code: "01011", label: "Soil conservation, soil testing and soil desalination services" },
  { code: "01012", label: "Hunting, trapping and game propagation services" },
  { code: "01013", label: "Growing of timber, plantation, operation of tree nurseries and conserving of forest" },
  { code: "01014", label: "Gathering of tendu leaves" },
  { code: "01015", label: "Gathering of other wild growing materials" },
  { code: "01016", label: "Forestry service activities, timber cruising, afforestation and reforestation" },
  { code: "01017", label: "Logging service activities, transport of logs within the forest" },
  { code: "01018", label: "Other agriculture, animal husbandry or forestry activity n.e.c" },
  { code: "02001", label: "Fishing on commercial basis in inland waters" },
  { code: "02002", label: "Fishing on commercial basis in ocean and coastal areas" },
  { code: "02003", label: "Fish farming" },
  { code: "02004", label: "Gathering of marine materials such as natural pearls, sponges, coral etc." },
  { code: "02005", label: "Services related to marine and fresh water fisheries, fish hatcheries and fish farms" },
  { code: "02006", label: "Other Fish farming activity n.e.c" },
  { code: "03001", label: "Mining and agglomeration of hard coal" },
  { code: "03002", label: "Mining and agglomeration of lignite" },
  { code: "03003", label: "Extraction and agglomeration of peat" },
  { code: "03004", label: "Extraction of crude petroleum and natural gas" },
  { code: "03005", label: "Service activities incidental to oil and gas extraction excluding surveying" },
  { code: "03006", label: "Mining of uranium and thorium ores" },
  { code: "03007", label: "Mining of iron ores" },
  { code: "03008", label: "Mining of non-ferrous metal ores, except uranium and thorium ores" },
  { code: "03009", label: "Mining of gemstones" },
  { code: "03010", label: "Mining of chemical and fertilizer minerals" },
  { code: "03011", label: "Mining of quarrying of abrasive materials" },
  { code: "03012", label: "Mining of mica, graphite and asbestos" },
  { code: "03013", label: "Quarrying of stones (marble/granite/dolomite), sand and clay" },
  { code: "03014", label: "Other mining and quarrying" },
  { code: "03015", label: "Mining and production of salt" },
  { code: "03016", label: "Other mining and quarrying n.e.c" },
  { code: "04001", label: "Production, processing and preservation of meat and meat products" },
  { code: "04002", label: "Production, processing and preservation of fish and fish products" },
  { code: "04003", label: "Manufacture of vegetable oil, animal oil and fats" },
  { code: "04004", label: "Processing of fruits, vegetables and edible nuts" },
  { code: "04005", label: "Manufacture of dairy products" },
  { code: "04006", label: "Manufacture of sugar" },
  { code: "04007", label: "Manufacture of cocoa, chocolates and sugar confectionery" },
  { code: "04008", label: "Flour milling" },
  { code: "04009", label: "Rice milling" },
  { code: "04010", label: "Dal milling" },
  { code: "04011", label: "Manufacture of other grain mill products" },
  { code: "04012", label: "Manufacture of bakery products" },
  { code: "04013", label: "Manufacture of starch products" },
  { code: "04014", label: "Manufacture of animal feeds" },
  { code: "04015", label: "Manufacture of other food products" },
  { code: "04016", label: "Manufacturing of wines" },
  { code: "04017", label: "Manufacture of beer" },
  { code: "04018", label: "Manufacture of malt liquors" },
  { code: "04019", label: "Distilling and blending of spirits, production of ethyl alcohol" },
  { code: "04020", label: "Manufacture of mineral water" },
  { code: "04021", label: "Manufacture of soft drinks" },
  { code: "04022", label: "Manufacture of other non-alcoholic beverages" },
  { code: "04023", label: "Manufacture of tobacco products" },
  { code: "04024", label: "Manufacture of textiles (other than by handloom)" },
  { code: "04025", label: "Manufacture of textiles using handlooms (khadi)" },
  { code: "04026", label: "Manufacture of carpet, rugs, blankets, shawls etc. (other than by hand)" },
  { code: "04027", label: "Manufacture of carpet, rugs, blankets, shawls etc. by hand" },
  { code: "04028", label: "Manufacture of wearing apparel" },
  { code: "04029", label: "Tanning and dressing of leather" },
  { code: "04030", label: "Manufacture of luggage, handbags and the like saddler and harness" },
  { code: "04031", label: "Manufacture of footwear" },
  { code: "04032", label: "Manufacture of wood and wood products, cork, straw and plaiting material" },
  { code: "04033", label: "Manufacture of paper and paper products" },
  { code: "04034", label: "Publishing, printing and reproduction of recorded media" },
  { code: "04035", label: "Manufacture of coke oven products" },
  { code: "04036", label: "Manufacture of refined petroleum products" },
  { code: "04037", label: "Processing of nuclear fuel" },
  { code: "04038", label: "Manufacture of fertilizers and nitrogen compounds" },
  { code: "04039", label: "Manufacture of plastics in primary forms and of synthetic rubber" },
  { code: "04040", label: "Manufacture of paints, varnishes and similar coatings" },
  { code: "04041", label: "Manufacture of pharmaceuticals, medicinal chemicals and botanical products" },
  { code: "04042", label: "Manufacture of soap and detergents" },
  { code: "04043", label: "Manufacture of other chemical products" },
  { code: "04044", label: "Manufacture of man-made fibers" },
  { code: "04045", label: "Manufacture of rubber products" },
  { code: "04046", label: "Manufacture of plastic products" },
  { code: "04047", label: "Manufacture of glass and glass products" },
  { code: "04048", label: "Manufacture of cement, lime and plaster" },
  { code: "04049", label: "Manufacture of articles of concrete, cement and plaster" },
  { code: "04050", label: "Manufacture of Bricks" },
  { code: "04051", label: "Manufacture of other clay and ceramic products" },
  { code: "04052", label: "Manufacture of other non-metallic mineral products" },
  { code: "04053", label: "Manufacture of pig iron, sponge iron, Direct Reduced Iron etc." },
  { code: "04054", label: "Manufacture of Ferro alloys" },
  { code: "04055", label: "Manufacture of Ingots, billets, blooms and slabs etc." },
  { code: "04056", label: "Manufacture of steel products" },
  { code: "04057", label: "Manufacture of basic precious and non-ferrous metals" },
  { code: "04058", label: "Manufacture of non-metallic mineral products" },
  { code: "04059", label: "Casting of metals" },
  { code: "04060", label: "Manufacture of fabricated metal products" },
  { code: "04061", label: "Manufacture of engines and turbines" },
  { code: "04062", label: "Manufacture of pumps and compressors" },
  { code: "04063", label: "Manufacture of bearings and gears" },
  { code: "04064", label: "Manufacture of ovens and furnaces" },
  { code: "04065", label: "Manufacture of lifting and handling equipment" },
  { code: "04066", label: "Manufacture of other general purpose machinery" },
  { code: "04067", label: "Manufacture of agricultural and forestry machinery" },
  { code: "04068", label: "Manufacture of Machine Tools" },
  { code: "04069", label: "Manufacture of machinery for metallurgy" },
  { code: "04070", label: "Manufacture of machinery for mining, quarrying and constructions" },
  { code: "04071", label: "Manufacture of machinery for processing of food and beverages" },
  { code: "04072", label: "Manufacture of machinery for leather and textile" },
  { code: "04073", label: "Manufacture of weapons and ammunition" },
  { code: "04074", label: "Manufacture of other special purpose machinery" },
  { code: "04075", label: "Manufacture of domestic appliances" },
  { code: "04076", label: "Manufacture of office, accounting and computing machinery" },
  { code: "04077", label: "Manufacture of electrical machinery and apparatus" },
  { code: "04078", label: "Manufacture of Radio, Television, communication equipment and apparatus" },
  { code: "04079", label: "Manufacture of medical and surgical equipment" },
  { code: "04080", label: "Manufacture of industrial process control equipment" },
  { code: "04081", label: "Manufacture of instruments and appliances for measurements and navigation" },
  { code: "04082", label: "Manufacture of optical instruments" },
  { code: "04083", label: "Manufacture of watches and clocks" },
  { code: "04084", label: "Manufacture of motor vehicles" },
  { code: "04085", label: "Manufacture of body of motor vehicles" },
  { code: "04086", label: "Manufacture of parts and accessories of motor vehicles and engines" },
  { code: "04087", label: "Building and repair of ships and boats" },
  { code: "04088", label: "Manufacture of railway locomotive and rolling stocks" },
  { code: "04089", label: "Manufacture of aircraft and spacecraft" },
  { code: "04090", label: "Manufacture of bicycles" },
  { code: "04091", label: "Manufacture of other transport equipment" },
  { code: "04092", label: "Manufacture of furniture" },
  { code: "04093", label: "Manufacture of jewellery" },
  { code: "04094", label: "Manufacture of sports goods" },
  { code: "04095", label: "Manufacture of musical instruments" },
  { code: "04096", label: "Manufacture of games and toys" },
  { code: "04097", label: "Other manufacturing n.e.c." },
  { code: "04098", label: "Recycling of metal waste and scrap" },
  { code: "04099", label: "Recycling of non- metal waste and scrap" },
  { code: "05001", label: "Production, collection and distribution of electricity" },
  { code: "05002", label: "Manufacture and distribution of gas" },
  { code: "05003", label: "Collection, purification and distribution of water" },
  { code: "05004", label: "Other essential commodity service n.e.c" },
  { code: "06001", label: "Site preparation works" },
  { code: "06002", label: "Building of complete constructions or parts- civil contractors" },
  { code: "06003", label: "Building installation" },
  { code: "06004", label: "Building completion" },
  { code: "06005", label: "Construction and maintenance of roads, rails, bridges, tunnels, ports, harbour, runways etc." },
  { code: "06006", label: "Construction and maintenance of power plants" },
  { code: "06007", label: "Construction and maintenance of industrial plants" },
  { code: "06008", label: "Construction and maintenance of power transmission and telecommunication lines" },
  { code: "06009", label: "Construction of water ways and water reservoirs" },
  { code: "06010", label: "Other construction activity n.e.c." },
  { code: "07001", label: "Purchase, sale and letting of leased buildings (residential and non-residential)" },
  { code: "07002", label: "Operating of real estate of self-owned buildings (residential and non-residential)" },
  { code: "07003", label: "Developing and sub-dividing real estate into lots" },
  { code: "07004", label: "Real estate activities on a fee or contract basis" },
  { code: "07005", label: "Other real estate/renting services n.e.c" },
  { code: "08001", label: "Renting of land transport equipment" },
  { code: "08002", label: "Renting of water transport equipment" },
  { code: "08003", label: "Renting of air transport equipment" },
  { code: "08004", label: "Renting of agricultural machinery and equipment" },
  { code: "08005", label: "Renting of construction and civil engineering machinery" },
  { code: "08006", label: "Renting of office machinery and equipment" },
  { code: "08007", label: "Renting of other machinery and equipment n.e.c." },
  { code: "08008", label: "Renting of personal and household goods n.e.c." },
  { code: "08009", label: "Renting of other machinery n.e.c." },
  { code: "09001", label: "Wholesale and retail sale of motor vehicles" },
  { code: "09002", label: "Repair and maintenance of motor vehicles" },
  { code: "09003", label: "Sale of motor parts and accessories- wholesale and retail" },
  { code: "09004", label: "Retail sale of automotive fuel" },
  { code: "09006", label: "Wholesale of agricultural raw material" },
  { code: "09007", label: "Wholesale of food and beverages and tobacco" },
  { code: "09008", label: "Wholesale of household goods" },
  { code: "09009", label: "Wholesale of metals and metal ores" },
  { code: "09010", label: "Wholesale of household goods" },
  { code: "09011", label: "Wholesale of construction material" },
  { code: "09012", label: "Wholesale of hardware and sanitary fittings" },
  { code: "09013", label: "Wholesale of cotton and jute" },
  { code: "09014", label: "Wholesale of raw wool and raw silk" },
  { code: "09015", label: "Wholesale of other textile fibres" },
  { code: "09016", label: "Wholesale of industrial chemicals" },
  { code: "09017", label: "Wholesale of fertilizers and pesticides" },
  { code: "09018", label: "Wholesale of electronic parts and equipment" },
  { code: "09019", label: "Wholesale of other machinery, equipment and supplies" },
  { code: "09020", label: "Wholesale of waste, scrap and materials for re-cycling" },
  { code: "09021", label: "Retail sale of food, beverages and tobacco in specialized stores" },
  { code: "09022", label: "Retail sale of other goods in specialized stores" },
  { code: "09023", label: "Retail sale in non-specialized stores" },
  { code: "09024", label: "Retail sale of textiles, apparel, footwear, leather goods" },
  { code: "09025", label: "Retail sale of other household appliances" },
  { code: "09026", label: "Retail sale of hardware, paint and glass" },
  { code: "09027", label: "Wholesale of other products n.e.c" },
  { code: "09028", label: "Retail sale of other products n.e.c" },
  { code: "09029", label: "Commission agents - Kachcha Arahtia" },
  { code: "10001", label: "Hotels – Star rated" },
  { code: "10002", label: "Hotels – Non-star rated" },
  { code: "10003", label: "Motels, Inns and Dharmshalas" },
  { code: "10004", label: "Guest houses and circuit houses" },
  { code: "10005", label: "Dormitories and hostels at educational institutions" },
  { code: "10006", label: "Short stay accommodations n.e.c." },
  { code: "10007", label: "Restaurants – with bars" },
  { code: "10008", label: "Restaurants – without bars" },
  { code: "10009", label: "Canteens" },
  { code: "10010", label: "Independent caterers" },
  { code: "10011", label: "Casinos and other games of chance" },
  { code: "10012", label: "Other hospitality services n.e.c." },
  { code: "11001", label: "Travel agencies and tour operators" },
  { code: "11002", label: "Packers and movers" },
  { code: "11003", label: "Passenger land transport" },
  { code: "11004", label: "Air transport" },
  { code: "11005", label: "Transport by urban/sub-urban railways" },
  { code: "11006", label: "Inland water transport" },
  { code: "11007", label: "Sea and coastal water transport" },
  { code: "11008", label: "Freight transport by road" },
  { code: "11009", label: "Freight transport by railways" },
  { code: "11010", label: "Forwarding of freight" },
  { code: "11011", label: "Receiving and acceptance of freight" },
  { code: "11012", label: "Cargo handling" },
  { code: "11013", label: "Storage and warehousing" },
  { code: "11014", label: "Transport via pipelines (transport of gases, liquids, slurry and other commodities)" },
  { code: "11015", label: "Other Transport and Logistics services n.e.c" },
  { code: "12001", label: "Post and courier activities" },
  { code: "12002", label: "Basic telecom services" },
  { code: "12003", label: "Value added telecom services" },
  { code: "12004", label: "Maintenance of telecom network" },
  { code: "12005", label: "Activities of the cable operators" },
  { code: "12006", label: "Other Post and Telecommunication services n.e.c" },
  { code: "13001", label: "Commercial banks, saving banks and discount houses" },
  { code: "13002", label: "Specialised institutions granting credit" },
  { code: "13003", label: "Financial leasing" },
  { code: "13004", label: "Hire-purchase financing" },
  { code: "13005", label: "Housing finance activities" },
  { code: "13006", label: "Commercial loan activities" },
  { code: "13007", label: "Credit cards" },
  { code: "13008", label: "Mutual funds" },
  { code: "13009", label: "Chit fund" },
  { code: "13010", label: "Investment activities" },
  { code: "13011", label: "Life insurance" },
  { code: "13012", label: "Pension funding" },
  { code: "13013", label: "Non-life insurance" },
  { code: "13014", label: "Administration of financial markets" },
  { code: "13015", label: "Stock brokers, sub-brokers and related activities" },
  { code: "13016", label: "Financial advisers, mortgage advisers and brokers" },
  { code: "13017", label: "Foreign exchange services" },
  { code: "13018", label: "Other financial intermediation services n.e.c." },
  { code: "14001", label: "Software development" },
  { code: "14002", label: "Other software consultancy" },
  { code: "14003", label: "Data processing" },
  { code: "14004", label: "Database activities and distribution of electronic content" },
  { code: "14005", label: "Other IT enabled services" },
  { code: "14006", label: "BPO services" },
  { code: "14007", label: "Cyber café" },
  { code: "14008", label: "Maintenance and repair of office, accounting and computing machinery" },
  { code: "14009", label: "Computer training and educational institutes" },
  { code: "14010", label: "Other computation related services n.e.c." },
  { code: "15001", label: "Natural sciences and engineering" },
  { code: "15002", label: "Social sciences and humanities" },
  { code: "15003", label: "Other Research and Development activities n.e.c." },
  { code: "16001", label: "Legal profession" },
  { code: "16002", label: "Accounting, book-keeping and auditing profession" },
  { code: "16003", label: "Tax consultancy" },
  { code: "16004", label: "Architectural profession" },
  { code: "16005", label: "Engineering and technical consultancy" },
  { code: "16006", label: "Advertising" },
  { code: "16007", label: "Fashion designing" },
  { code: "16008", label: "Interior decoration" },
  { code: "16009", label: "Photography" },
  { code: "16010", label: "Auctioneers" },
  { code: "16012", label: "Market research and public opinion polling" },
  { code: "16013", label: "Business and management consultancy activities" },
  { code: "16014", label: "Labour recruitment and provision of personnel" },
  { code: "16015", label: "Investigation and security services" },
  { code: "16016", label: "Building-cleaning and industrial cleaning activities" },
  { code: "16017", label: "Packaging activities" },
  { code: "16018", label: "Secretarial activities , 16019_1 - Medical Profession" },
  { code: "16019", label: "Other professional services n.e.c." },
  { code: "16020", label: "Film Artist" },
  { code: "16021", label: "Social Media Influencers" },
  { code: "17001", label: "Primary education" },
  { code: "17002", label: "Secondary/ senior secondary education" },
  { code: "17003", label: "Technical and vocational secondary/ senior secondary education" },
  { code: "17004", label: "Higher education" },
  { code: "17005", label: "Education by correspondence" },
  { code: "17006", label: "Coaching centres and tuitions" },
  { code: "17007", label: "Other education services n.e.c." },
  { code: "18001", label: "General hospitals" },
  { code: "18002", label: "Speciality and super speciality hospitals" },
  { code: "18003", label: "Nursing homes" },
  { code: "18004", label: "Diagnostic centres" },
  { code: "18005", label: "Pathological laboratories" },
  { code: "18006", label: "Independent blood banks" },
  { code: "18007", label: "Medical transcription" },
  { code: "18008", label: "Independent ambulance services" },
  { code: "18009", label: "Medical suppliers, agencies and stores" },
  { code: "18010", label: "Medical clinics" },
  { code: "18011", label: "Dental practice" },
  { code: "18012", label: "Ayurveda practice" },
  { code: "18013", label: "Unani practice" },
  { code: "18014", label: "Homeopathy practice" },
  { code: "18015", label: "Nurses, physiotherapists or other para-medical practitioners" },
  { code: "18016", label: "Veterinary hospitals and practice" },
  { code: "18017", label: "Medical education" },
  { code: "18018", label: "Medical research" },
  { code: "18019", label: "Practice of other alternative medicine" },
  { code: "18020", label: "Other healthcare services" },
  { code: "19001", label: "Social work activities with accommodation (orphanages and old age homes)" },
  { code: "19002", label: "Social work activities without accommodation (Creches)" },
  { code: "19003", label: "Industry associations, chambers of commerce" },
  { code: "19004", label: "Professional organisations" },
  { code: "19005", label: "Trade unions" },
  { code: "19006", label: "Religious organizations" },
  { code: "19007", label: "Political organisations" },
  { code: "19008", label: "Other membership organisations n.e.c. (rotary clubs, book clubs and philatelic clubs)" },
  { code: "19009", label: "Other Social or community service n.e.c" },
  { code: "20001", label: "Motion picture production" },
  { code: "20002", label: "Film distribution" },
  { code: "20003", label: "Film laboratories" },
  { code: "20004", label: "Television channel productions" },
  { code: "20005", label: "Television channels broadcast" },
  { code: "20006", label: "Video production and distribution" },
  { code: "20007", label: "Sound recording studios" },
  { code: "20008", label: "Radio - recording and distribution" },
  { code: "20009", label: "Stage production and related activities" },
  { code: "20010", label: "Individual artists excluding authors" },
  { code: "20011", label: "Literary activities" },
  { code: "20012", label: "Other cultural activities n.e.c." },
  { code: "20013", label: "Circuses and race tracks" },
  { code: "20014", label: "Video Parlours" },
  { code: "20015", label: "News agency activities" },
  { code: "20016", label: "Library and archives activities" },
  { code: "20017", label: "Museum activities" },
  { code: "20018", label: "Preservation of historical sites and buildings" },
  { code: "20019", label: "Botanical and zoological gardens" },
  { code: "20020", label: "Operation and maintenance of sports facilities" },
  { code: "20021", label: "Activities of sports and game schools" },
  { code: "20022", label: "Organisation and operation of indoor/outdoor sports and promotion and production of sporting events , 20023_1 - Sports Management" },
  { code: "20023", label: "Other sporting activities n.e.c." },
  { code: "20024", label: "Other recreational activities n.e.c." },
  { code: "21001", label: "Hair dressing and other beauty treatment" },
  { code: "21002", label: "Funeral and related activities" },
  { code: "21003", label: "Marriage bureaus" },
  { code: "21004", label: "Pet care services" },
  { code: "21005", label: "Sauna and steam baths, massage salons etc." },
  { code: "21006", label: "Astrological and spiritualists’ activities" },
  { code: "21007", label: "Private households as employers of domestic staff , 21008_1 - Event Management" },
  { code: "21008", label: "Other services n.e.c." },
  { code: "21009", label: "Speculative trading" },
  { code: "21010", label: "Futures and Options trading" },
  { code: "21011", label: "Buying and selling shares" },
  { code: "22001", label: "Extra territorial organisations and bodies (IMF, World Bank,European Commission etc.)" },
] as const;

export type NATURE_OF_BUSINESSCode = typeof NATURE_OF_BUSINESS[number]['code'];
