/**
 * ICAI Technical Guide on Financial Statements of Non-Corporate
 * Entities (2023) — Excel emission for proprietorships, partnership
 * firms, LLPs, AOPs, and other non-corporate entities.
 *
 * Structurally similar to Schedule III but with non-corporate
 * terminology:
 *   - "Share capital" → "Partners' / Proprietor's capital"
 *   - "Reserves and surplus" → "Reserves"
 *   - Section numbering follows the Technical Guide rather than
 *     Schedule III's I/II/III(a) convention
 *
 * Same canonical aggregate as Schedule III; the exporter pulls
 * from `ScheduleThreeReport` and relabels for display. No new math.
 *
 * Two-sheet output (BS only — non-corporate entities don't have a
 * statutorily-mandated P&L format like Schedule III's Statement of
 * P&L, so we surface that as an optional sheet using the same
 * line items but a simpler vertical layout).
 */

import ExcelJS from 'exceljs';
import type { TbBsDraft } from './uiModel';
import type { ScheduleThreeReport } from './scheduleThreeBuilder';
import type { ScheduleThreeSection } from './scheduleThreeAccounts';

const RUPEE_FMT = '#,##,##0;[Red](#,##,##0);"—"';
const SECTION_FILL: ExcelJS.FillPattern = {
  type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' },
};
const TOTAL_FILL: ExcelJS.FillPattern = {
  type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE6F4EA' },
};

export interface IcaiNcExportInput {
  draft: TbBsDraft;
  report: ScheduleThreeReport;
}

export async function buildIcaiNonCorporateWorkbook(input: IcaiNcExportInput): Promise<Blob> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Smartbiz Tax Assistant';
  wb.created = new Date();

  buildCover(wb, input);
  buildBalanceSheet(wb, input);
  buildStatementOfPL(wb, input);

  const buf = await wb.xlsx.writeBuffer();
  return new Blob([buf as ArrayBuffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
}

// ── Helpers ─────────────────────────────────────────────────────

function cellRef(row: number, col: number): string {
  let s = '';
  let c = col;
  while (c > 0) {
    const rem = (c - 1) % 26;
    s = String.fromCharCode(65 + rem) + s;
    c = Math.floor((c - 1) / 26);
  }
  return `${s}${row}`;
}

function roundInt(n: number): number {
  return Number.isFinite(n) ? Math.round(n) : 0;
}

function buildCover(wb: ExcelJS.Workbook, input: IcaiNcExportInput) {
  const ws = wb.addWorksheet('Cover');
  ws.columns = [{ width: 28 }, { width: 60 }];
  ws.addRow(['FINANCIAL STATEMENTS']).font = { bold: true, size: 14 };
  ws.addRow(['ICAI Technical Guide on Non-Corporate Entities (2023)']).font = { italic: true, color: { argb: 'FF6B7280' } };
  ws.addRow([]);
  ws.addRow(['Name', input.draft.firm?.firmName ?? '—']);
  ws.addRow(['GSTIN', input.draft.firm?.gstin ?? '—']);
  ws.addRow(['Registered office', input.draft.firm?.registeredOffice ?? '—']);
  ws.addRow([]);
  ws.addRow(['Current year', input.report.currentLabel]);
  if (input.report.hasPreviousYear) {
    ws.addRow(['Previous year', input.report.previousLabel]);
  }
  ws.addRow([]);
  ws.addRow(['Generated by', 'Smartbiz Tax Assistant — formulas live for audit. Format per ICAI Technical Guide 2023.']).font = { italic: true, color: { argb: 'FF6B7280' } };
  ws.getColumn(1).font = { bold: true };
}

function colHeader(ws: ExcelJS.Worksheet, currentLabel: string, previousLabel: string, hasPrev: boolean) {
  const header = ws.addRow(['Particulars', currentLabel, ...(hasPrev ? [previousLabel] : [])]);
  header.font = { bold: true };
  header.eachCell((c, n) => {
    if (n > 1) {
      c.fill = SECTION_FILL;
      c.alignment = { horizontal: 'right' };
    }
  });
}

function buildBalanceSheet(wb: ExcelJS.Workbook, input: IcaiNcExportInput) {
  const ws = wb.addWorksheet('Balance Sheet');
  const { report } = input;
  const hasPrev = report.hasPreviousYear;

  ws.addRow([`${input.draft.firm?.firmName ?? '—'}`]).font = { bold: true, size: 12 };
  ws.addRow(['Balance Sheet as at year-end']).font = { italic: true, color: { argb: 'FF6B7280' } };
  ws.addRow([]);
  colHeader(ws, report.currentLabel, report.previousLabel, hasPrev);
  ws.addRow([]);

  const rowMap = new Map<ScheduleThreeSection, number>();

  const writeLine = (key: ScheduleThreeSection, label: string) => {
    const agg = report.aggregate[key];
    const cur = agg?.current ?? 0;
    const prev = agg?.previous ?? 0;
    if (Math.abs(cur) < 0.01 && Math.abs(prev) < 0.01) return;
    const row = ws.addRow([`  ${label}`, roundInt(cur), ...(hasPrev ? [roundInt(prev)] : [])]);
    row.getCell(2).numFmt = RUPEE_FMT;
    if (hasPrev) row.getCell(3).numFmt = RUPEE_FMT;
    rowMap.set(key, row.number);
  };

  const writeSection = (heading: string) => {
    const r = ws.addRow([heading]);
    r.font = { bold: true };
    r.getCell(1).fill = SECTION_FILL;
  };

  const writeSubtotal = (label: string, keys: ScheduleThreeSection[]) => {
    const refs = keys.map((k) => rowMap.get(k)).filter((r): r is number => typeof r === 'number');
    if (refs.length === 0) {
      const r = ws.addRow([label, 0, ...(hasPrev ? [0] : [])]);
      r.font = { bold: true };
      r.getCell(2).numFmt = RUPEE_FMT;
      if (hasPrev) r.getCell(3).numFmt = RUPEE_FMT;
      return r.number;
    }
    const row = ws.addRow([
      label,
      { formula: refs.map((r) => cellRef(r, 2)).join('+') },
      ...(hasPrev ? [{ formula: refs.map((r) => cellRef(r, 3)).join('+') }] : []),
    ]);
    row.font = { bold: true };
    row.getCell(2).numFmt = RUPEE_FMT;
    row.getCell(2).fill = TOTAL_FILL;
    if (hasPrev) { row.getCell(3).numFmt = RUPEE_FMT; row.getCell(3).fill = TOTAL_FILL; }
    return row.number;
  };

  // ── EQUITY AND LIABILITIES ────────────────────────────────────
  writeSection('I. EQUITY AND LIABILITIES');

  writeSection(' (1) Partners\' / Proprietor\'s funds');
  writeLine('bs_share_capital', '(a) Partners\' / Proprietor\'s capital');
  writeLine('bs_reserves_surplus', '(b) Reserves');
  const partnersFundsRow = writeSubtotal('Total Partners\' / Proprietor\'s funds', [
    'bs_share_capital', 'bs_reserves_surplus',
  ]);

  writeSection(' (2) Non-current liabilities');
  writeLine('bs_long_term_borrowings', '(a) Long-term borrowings');
  writeLine('bs_deferred_tax_liab', '(b) Deferred tax liabilities (net)');
  writeLine('bs_other_long_term_liab', '(c) Other long-term liabilities');
  writeLine('bs_long_term_provisions', '(d) Long-term provisions');
  const nonCurrentLiabRow = writeSubtotal('Total non-current liabilities', [
    'bs_long_term_borrowings', 'bs_deferred_tax_liab', 'bs_other_long_term_liab', 'bs_long_term_provisions',
  ]);

  writeSection(' (3) Current liabilities');
  writeLine('bs_short_term_borrowings', '(a) Short-term borrowings');
  writeLine('bs_trade_payables', '(b) Trade payables');
  writeLine('bs_other_current_liab', '(c) Other current liabilities');
  writeLine('bs_short_term_provisions', '(d) Short-term provisions');
  const currentLiabRow = writeSubtotal('Total current liabilities', [
    'bs_short_term_borrowings', 'bs_trade_payables', 'bs_other_current_liab', 'bs_short_term_provisions',
  ]);

  const liabSubtotals = [partnersFundsRow, nonCurrentLiabRow, currentLiabRow];
  const totalEqLiabRow = ws.addRow([
    'TOTAL EQUITY AND LIABILITIES',
    { formula: liabSubtotals.map((r) => cellRef(r, 2)).join('+') },
    ...(hasPrev ? [{ formula: liabSubtotals.map((r) => cellRef(r, 3)).join('+') }] : []),
  ]);
  totalEqLiabRow.font = { bold: true };
  totalEqLiabRow.eachCell((c, n) => {
    if (n > 1) {
      c.numFmt = RUPEE_FMT;
      c.fill = TOTAL_FILL;
      c.border = { top: { style: 'thin' }, bottom: { style: 'double' } };
    }
  });
  ws.addRow([]);

  // ── ASSETS ────────────────────────────────────────────────────
  writeSection('II. ASSETS');

  writeSection(' (1) Non-current assets');
  writeLine('bs_tangible_assets', '(a)(i) Property, plant and equipment (tangible)');
  writeLine('bs_intangible_assets', '(a)(ii) Intangible assets');
  writeLine('bs_capital_wip', '(a)(iii) Capital work-in-progress');
  writeLine('bs_intangible_under_dev', '(a)(iv) Intangible assets under development');
  writeLine('bs_non_current_investments', '(b) Non-current investments');
  writeLine('bs_deferred_tax_asset', '(c) Deferred tax assets (net)');
  writeLine('bs_long_term_loans_advances', '(d) Long-term loans and advances');
  writeLine('bs_other_non_current_assets', '(e) Other non-current assets');
  const nonCurrentAssetsRow = writeSubtotal('Total non-current assets', [
    'bs_tangible_assets', 'bs_intangible_assets', 'bs_capital_wip', 'bs_intangible_under_dev',
    'bs_non_current_investments', 'bs_deferred_tax_asset', 'bs_long_term_loans_advances', 'bs_other_non_current_assets',
  ]);

  writeSection(' (2) Current assets');
  writeLine('bs_current_investments', '(a) Current investments');
  writeLine('bs_inventories', '(b) Inventories');
  writeLine('bs_trade_receivables', '(c) Trade receivables');
  writeLine('bs_cash_equivalents', '(d) Cash and cash equivalents');
  writeLine('bs_short_term_loans_advances', '(e) Short-term loans and advances');
  writeLine('bs_other_current_assets', '(f) Other current assets');
  const currentAssetsRow = writeSubtotal('Total current assets', [
    'bs_current_investments', 'bs_inventories', 'bs_trade_receivables', 'bs_cash_equivalents',
    'bs_short_term_loans_advances', 'bs_other_current_assets',
  ]);

  const assetsSubtotals = [nonCurrentAssetsRow, currentAssetsRow];
  const totalAssetsRow = ws.addRow([
    'TOTAL ASSETS',
    { formula: assetsSubtotals.map((r) => cellRef(r, 2)).join('+') },
    ...(hasPrev ? [{ formula: assetsSubtotals.map((r) => cellRef(r, 3)).join('+') }] : []),
  ]);
  totalAssetsRow.font = { bold: true };
  totalAssetsRow.eachCell((c, n) => {
    if (n > 1) {
      c.numFmt = RUPEE_FMT;
      c.fill = TOTAL_FILL;
      c.border = { top: { style: 'thin' }, bottom: { style: 'double' } };
    }
  });

  // Balance-check italics row
  ws.addRow([]);
  const balanceCheck = ws.addRow([
    'Balance check (assets − liabilities)',
    { formula: `${cellRef(totalAssetsRow.number, 2)}-${cellRef(totalEqLiabRow.number, 2)}` },
    ...(hasPrev ? [{ formula: `${cellRef(totalAssetsRow.number, 3)}-${cellRef(totalEqLiabRow.number, 3)}` }] : []),
  ]);
  balanceCheck.font = { italic: true, color: { argb: 'FF6B7280' } };
  balanceCheck.getCell(2).numFmt = RUPEE_FMT;
  if (hasPrev) balanceCheck.getCell(3).numFmt = RUPEE_FMT;

  ws.getColumn(1).width = 56;
  ws.getColumn(2).width = 18;
  if (hasPrev) ws.getColumn(3).width = 18;
}

function buildStatementOfPL(wb: ExcelJS.Workbook, input: IcaiNcExportInput) {
  const ws = wb.addWorksheet('Statement of P&L');
  const { report } = input;
  const hasPrev = report.hasPreviousYear;

  ws.addRow([`${input.draft.firm?.firmName ?? '—'}`]).font = { bold: true, size: 12 };
  ws.addRow(['Statement of Profit and Loss for the year ended']).font = { italic: true, color: { argb: 'FF6B7280' } };
  ws.addRow([]);
  colHeader(ws, report.currentLabel, report.previousLabel, hasPrev);
  ws.addRow([]);

  // P&L for non-corporate is structurally the same as Schedule III's
  // — Indian Income Tax Act conventions don't dictate a different
  // P&L layout for non-corporates. We reuse the structure verbatim.
  const rowMap = new Map<ScheduleThreeSection, number>();

  const writeLine = (key: ScheduleThreeSection, label: string) => {
    const agg = report.aggregate[key];
    const cur = agg?.current ?? 0;
    const prev = agg?.previous ?? 0;
    if (Math.abs(cur) < 0.01 && Math.abs(prev) < 0.01) return;
    const row = ws.addRow([`  ${label}`, roundInt(cur), ...(hasPrev ? [roundInt(prev)] : [])]);
    row.getCell(2).numFmt = RUPEE_FMT;
    if (hasPrev) row.getCell(3).numFmt = RUPEE_FMT;
    rowMap.set(key, row.number);
  };

  const writeSection = (heading: string) => {
    const r = ws.addRow([heading]);
    r.font = { bold: true };
    r.getCell(1).fill = SECTION_FILL;
  };

  const writeSubtotal = (label: string, keys: ScheduleThreeSection[]) => {
    const refs = keys.map((k) => rowMap.get(k)).filter((r): r is number => typeof r === 'number');
    if (refs.length === 0) {
      const r = ws.addRow([label, 0, ...(hasPrev ? [0] : [])]);
      r.font = { bold: true };
      r.getCell(2).numFmt = RUPEE_FMT;
      if (hasPrev) r.getCell(3).numFmt = RUPEE_FMT;
      return r.number;
    }
    const row = ws.addRow([
      label,
      { formula: refs.map((r) => cellRef(r, 2)).join('+') },
      ...(hasPrev ? [{ formula: refs.map((r) => cellRef(r, 3)).join('+') }] : []),
    ]);
    row.font = { bold: true };
    row.getCell(2).numFmt = RUPEE_FMT;
    row.getCell(2).fill = TOTAL_FILL;
    if (hasPrev) { row.getCell(3).numFmt = RUPEE_FMT; row.getCell(3).fill = TOTAL_FILL; }
    return row.number;
  };

  writeSection('Income');
  writeLine('pl_revenue_operations', 'Revenue from operations');
  writeLine('pl_other_income', 'Other income');
  const totalRevenueRow = writeSubtotal('Total income', ['pl_revenue_operations', 'pl_other_income']);

  ws.addRow([]);
  writeSection('Expenses');
  writeLine('pl_cost_of_materials', 'Cost of materials consumed');
  writeLine('pl_purchases_stock', 'Purchases of stock-in-trade');
  writeLine('pl_change_inventory', 'Changes in inventories');
  writeLine('pl_employee_benefits', 'Employee benefits expense');
  writeLine('pl_finance_costs', 'Finance costs');
  writeLine('pl_depreciation_amort', 'Depreciation and amortization');
  writeLine('pl_other_expenses', 'Other expenses');
  const expensesRow = writeSubtotal('Total expenses', [
    'pl_cost_of_materials', 'pl_purchases_stock', 'pl_change_inventory',
    'pl_employee_benefits', 'pl_finance_costs', 'pl_depreciation_amort', 'pl_other_expenses',
  ]);

  const pbtRow = ws.addRow([
    'Profit before tax',
    { formula: `${cellRef(totalRevenueRow, 2)}-${cellRef(expensesRow, 2)}` },
    ...(hasPrev ? [{ formula: `${cellRef(totalRevenueRow, 3)}-${cellRef(expensesRow, 3)}` }] : []),
  ]);
  pbtRow.font = { bold: true };
  pbtRow.getCell(2).numFmt = RUPEE_FMT;
  if (hasPrev) pbtRow.getCell(3).numFmt = RUPEE_FMT;

  writeSection('Tax expense');
  writeLine('pl_tax_current', 'Current tax');
  writeLine('pl_tax_deferred', 'Deferred tax');
  const taxRow = writeSubtotal('Total tax expense', ['pl_tax_current', 'pl_tax_deferred']);

  const patRow = ws.addRow([
    'Profit for the period',
    { formula: `${cellRef(pbtRow.number, 2)}-${cellRef(taxRow, 2)}` },
    ...(hasPrev ? [{ formula: `${cellRef(pbtRow.number, 3)}-${cellRef(taxRow, 3)}` }] : []),
  ]);
  patRow.font = { bold: true };
  patRow.eachCell((c, n) => {
    if (n > 1) {
      c.numFmt = RUPEE_FMT;
      c.fill = TOTAL_FILL;
      c.border = { top: { style: 'thin' }, bottom: { style: 'double' } };
    }
  });

  ws.getColumn(1).width = 56;
  ws.getColumn(2).width = 18;
  if (hasPrev) ws.getColumn(3).width = 18;
}
