/**
 * Tally-style Balance Sheet — traditional 'Sources of Funds' /
 * 'Application of Funds' vertical layout. The de-facto standard
 * for non-corporate entities (proprietorships, partnership firms)
 * before the ICAI 2023 guide formalised the modern alternative.
 *
 * Layout:
 *
 *   SOURCES OF FUNDS
 *     1. Capital Account                  XXX
 *     2. Reserves & Surplus               XXX
 *     3. Loan Funds
 *        (a) Secured Loans                XXX
 *        (b) Unsecured Loans              XXX
 *     4. Deferred Tax Liability           XXX
 *                                      ━━━━━
 *     TOTAL SOURCES                      XXX
 *                                      ━━━━━
 *
 *   APPLICATION OF FUNDS
 *     1. Fixed Assets
 *        Gross Block                      XXX
 *        Less: Depreciation               XXX
 *        Net Block                        XXX
 *     2. Investments                      XXX
 *     3. Current Assets, Loans & Advances
 *        Inventories                      XXX
 *        Sundry Debtors                   XXX
 *        Cash & Bank                      XXX
 *        Other current assets             XXX
 *                                      ─────
 *        Less: Current Liabilities & Provisions
 *        Sundry Creditors                 XXX
 *        Other current liabilities        XXX
 *                                      ─────
 *        Net Current Assets               XXX
 *     4. Miscellaneous Expenditure        XXX
 *                                      ━━━━━
 *     TOTAL APPLICATION                  XXX
 *                                      ━━━━━
 *
 * "Secured / Unsecured" split: we don't have separate canonical
 * keys for these (the Schedule III chart we share groups them under
 * 'bs_long_term_borrowings'). For the Tally layout we surface ALL
 * long-term borrowings as 'Secured Loans' by default — the user
 * can edit the cell in the downloaded Excel if they want to split.
 * Future enhancement: add a 'secured?' flag in the mapping step.
 */

import ExcelJS from 'exceljs';
import type { TbBsDraft } from './uiModel';
import type { ScheduleThreeReport } from './scheduleThreeBuilder';
import type { ScheduleThreeSection } from './scheduleThreeAccounts';

const RUPEE_FMT = '#,##,##0;[Red](#,##,##0);"—"';
const SECTION_FILL: ExcelJS.FillPattern = {
  type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' },
};
const TOTAL_FILL: ExcelJS.FillPattern = {
  type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE6F4EA' },
};

export interface TallyVerticalExportInput {
  draft: TbBsDraft;
  report: ScheduleThreeReport;
}

export async function buildTallyVerticalWorkbook(input: TallyVerticalExportInput): Promise<Blob> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Smartbiz Tax Assistant';
  wb.created = new Date();

  buildCover(wb, input);
  buildBalanceSheet(wb, input);
  // P&L for Tally-style — uses the same simple vertical layout as
  // ICAI; no statutory difference at the P&L level.
  buildSimplifiedPL(wb, input);

  const buf = await wb.xlsx.writeBuffer();
  return new Blob([buf as ArrayBuffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
}

function cellRef(row: number, col: number): string {
  let s = '';
  let c = col;
  while (c > 0) {
    const rem = (c - 1) % 26;
    s = String.fromCharCode(65 + rem) + s;
    c = Math.floor((c - 1) / 26);
  }
  return `${s}${row}`;
}

function roundInt(n: number): number {
  return Number.isFinite(n) ? Math.round(n) : 0;
}

function buildCover(wb: ExcelJS.Workbook, input: TallyVerticalExportInput) {
  const ws = wb.addWorksheet('Cover');
  ws.columns = [{ width: 28 }, { width: 60 }];
  ws.addRow(['BALANCE SHEET']).font = { bold: true, size: 14 };
  ws.addRow(['Sources / Application of Funds — traditional vertical layout']).font = { italic: true, color: { argb: 'FF6B7280' } };
  ws.addRow([]);
  ws.addRow(['Name', input.draft.firm?.firmName ?? '—']);
  ws.addRow(['GSTIN', input.draft.firm?.gstin ?? '—']);
  ws.addRow(['Registered office', input.draft.firm?.registeredOffice ?? '—']);
  ws.addRow([]);
  ws.addRow(['Current year', input.report.currentLabel]);
  if (input.report.hasPreviousYear) {
    ws.addRow(['Previous year', input.report.previousLabel]);
  }
  ws.addRow([]);
  ws.addRow(['Generated by', 'Smartbiz Tax Assistant — formulas live for audit.']).font = { italic: true, color: { argb: 'FF6B7280' } };
  ws.getColumn(1).font = { bold: true };
}

function buildBalanceSheet(wb: ExcelJS.Workbook, input: TallyVerticalExportInput) {
  const ws = wb.addWorksheet('Balance Sheet');
  const { report } = input;
  const hasPrev = report.hasPreviousYear;

  ws.addRow([`${input.draft.firm?.firmName ?? '—'}`]).font = { bold: true, size: 12 };
  ws.addRow(['Balance Sheet as at year-end']).font = { italic: true, color: { argb: 'FF6B7280' } };
  ws.addRow([]);
  const header = ws.addRow(['Particulars', report.currentLabel, ...(hasPrev ? [report.previousLabel] : [])]);
  header.font = { bold: true };
  header.eachCell((c, n) => { if (n > 1) { c.fill = SECTION_FILL; c.alignment = { horizontal: 'right' }; } });
  ws.addRow([]);

  const rowMap = new Map<ScheduleThreeSection, number>();

  const writeLine = (key: ScheduleThreeSection, label: string, indent = 2) => {
    const agg = report.aggregate[key];
    const cur = agg?.current ?? 0;
    const prev = agg?.previous ?? 0;
    if (Math.abs(cur) < 0.01 && Math.abs(prev) < 0.01) return;
    const row = ws.addRow([`${' '.repeat(indent)}${label}`, roundInt(cur), ...(hasPrev ? [roundInt(prev)] : [])]);
    row.getCell(2).numFmt = RUPEE_FMT;
    if (hasPrev) row.getCell(3).numFmt = RUPEE_FMT;
    rowMap.set(key, row.number);
    return row.number;
  };

  const writeSection = (heading: string) => {
    const r = ws.addRow([heading]);
    r.font = { bold: true };
    r.getCell(1).fill = SECTION_FILL;
  };

  const writeSubLabel = (label: string) => {
    const r = ws.addRow([`  ${label}`]);
    r.font = { bold: true, color: { argb: 'FF6B7280' } };
  };

  const writeSubtotal = (label: string, formulaRefs: number[]) => {
    const refs = formulaRefs.filter((r): r is number => typeof r === 'number' && r > 0);
    if (refs.length === 0) {
      const r = ws.addRow([label, 0, ...(hasPrev ? [0] : [])]);
      r.font = { bold: true };
      r.getCell(2).numFmt = RUPEE_FMT;
      if (hasPrev) r.getCell(3).numFmt = RUPEE_FMT;
      return r.number;
    }
    const row = ws.addRow([
      label,
      { formula: refs.map((r) => cellRef(r, 2)).join('+') },
      ...(hasPrev ? [{ formula: refs.map((r) => cellRef(r, 3)).join('+') }] : []),
    ]);
    row.font = { bold: true };
    row.getCell(2).numFmt = RUPEE_FMT;
    row.getCell(2).fill = TOTAL_FILL;
    if (hasPrev) { row.getCell(3).numFmt = RUPEE_FMT; row.getCell(3).fill = TOTAL_FILL; }
    return row.number;
  };

  // ─── SOURCES OF FUNDS ────────────────────────────────────────
  writeSection('SOURCES OF FUNDS');

  writeSubLabel('1. Capital Account');
  const capRow = writeLine('bs_share_capital', 'Capital');
  writeSubLabel('2. Reserves & Surplus');
  const reservesRow = writeLine('bs_reserves_surplus', 'Reserves and Surplus');
  writeSubLabel('3. Loan Funds');
  // Secured / Unsecured come from the per-row `isUnsecured` flag on
  // each TbMappingEntry. The report's loanFundsSplit aggregates them
  // separately. When the user hasn't flagged anything as unsecured
  // (the default), securedLoans equals the full bs_long_term_borrowings
  // total and the unsecured line is suppressed (zero).
  let securedRow: number | undefined;
  let unsecuredRow: number | undefined;
  if (report.loanFundsSplit.secured[0] > 0 || report.loanFundsSplit.secured[1] > 0) {
    const r = ws.addRow([
      '    (a) Secured Loans',
      roundInt(report.loanFundsSplit.secured[0]),
      ...(hasPrev ? [roundInt(report.loanFundsSplit.secured[1])] : []),
    ]);
    r.getCell(2).numFmt = RUPEE_FMT;
    if (hasPrev) r.getCell(3).numFmt = RUPEE_FMT;
    securedRow = r.number;
  }
  if (report.loanFundsSplit.unsecured[0] > 0 || report.loanFundsSplit.unsecured[1] > 0) {
    const r = ws.addRow([
      '    (b) Unsecured Loans',
      roundInt(report.loanFundsSplit.unsecured[0]),
      ...(hasPrev ? [roundInt(report.loanFundsSplit.unsecured[1])] : []),
    ]);
    r.getCell(2).numFmt = RUPEE_FMT;
    if (hasPrev) r.getCell(3).numFmt = RUPEE_FMT;
    unsecuredRow = r.number;
  }
  // Short-term bank borrowings (CC / OD / WC loan) sit under Loan
  // Funds in the traditional Tally layout — the user can move
  // them to current liabilities by hand if they prefer.
  const stBorrowRow = writeLine('bs_short_term_borrowings', '(c) Short-term Borrowings');
  writeSubLabel('4. Deferred Tax Liability');
  const dtlRow = writeLine('bs_deferred_tax_liab', 'Deferred Tax Liability');
  const otherLongLiabRow = writeLine('bs_other_long_term_liab', '5. Other Long-term Liabilities');
  const longProvRow = writeLine('bs_long_term_provisions', '6. Long-term Provisions');

  const totalSourcesRow = writeSubtotal('TOTAL SOURCES OF FUNDS', [
    capRow ?? 0, reservesRow ?? 0,
    securedRow ?? 0, unsecuredRow ?? 0, stBorrowRow ?? 0,
    dtlRow ?? 0, otherLongLiabRow ?? 0, longProvRow ?? 0,
  ]);
  ws.getRow(totalSourcesRow).eachCell((c, n) => {
    if (n > 1) c.border = { top: { style: 'thin' }, bottom: { style: 'double' } };
  });
  ws.addRow([]);

  // ─── APPLICATION OF FUNDS ────────────────────────────────────
  writeSection('APPLICATION OF FUNDS');

  writeSubLabel('1. Fixed Assets');
  const tangibleRow = writeLine('bs_tangible_assets', 'Tangible Assets (Net Block)');
  const intangibleRow = writeLine('bs_intangible_assets', 'Intangible Assets');
  const cwipRow = writeLine('bs_capital_wip', 'Capital Work-in-Progress');
  const fixedAssetsTotalRow = writeSubtotal('Total Fixed Assets', [
    tangibleRow ?? 0, intangibleRow ?? 0, cwipRow ?? 0,
  ]);

  writeSubLabel('2. Investments');
  const ncInvRow = writeLine('bs_non_current_investments', 'Non-current Investments');
  const cInvRow = writeLine('bs_current_investments', 'Current Investments');
  const investmentsRow = writeSubtotal('Total Investments', [ncInvRow ?? 0, cInvRow ?? 0]);

  writeSubLabel('3. Current Assets, Loans & Advances');
  const invRow = writeLine('bs_inventories', 'Inventories');
  const recRow = writeLine('bs_trade_receivables', 'Sundry Debtors');
  const cashRow = writeLine('bs_cash_equivalents', 'Cash and Bank');
  const stAdvRow = writeLine('bs_short_term_loans_advances', 'Short-term Loans and Advances');
  const ltAdvRow = writeLine('bs_long_term_loans_advances', 'Long-term Loans and Advances');
  const otherCARow = writeLine('bs_other_current_assets', 'Other Current Assets');
  const totalCARow = writeSubtotal('Total Current Assets, Loans & Advances', [
    invRow ?? 0, recRow ?? 0, cashRow ?? 0, stAdvRow ?? 0, ltAdvRow ?? 0, otherCARow ?? 0,
  ]);

  writeSubLabel('  Less: Current Liabilities & Provisions');
  const credRow = writeLine('bs_trade_payables', 'Sundry Creditors', 4);
  const otherCLRow = writeLine('bs_other_current_liab', 'Other Current Liabilities', 4);
  const stProvRow = writeLine('bs_short_term_provisions', 'Short-term Provisions', 4);
  const totalCLRow = writeSubtotal('  Total Current Liabilities & Provisions', [
    credRow ?? 0, otherCLRow ?? 0, stProvRow ?? 0,
  ]);

  // Net Current Assets = total CA − total CL.
  const netCARow = ws.addRow([
    'Net Current Assets',
    totalCARow && totalCLRow
      ? { formula: `${cellRef(totalCARow, 2)}-${cellRef(totalCLRow, 2)}` }
      : 0,
    ...(hasPrev
      ? [totalCARow && totalCLRow
        ? { formula: `${cellRef(totalCARow, 3)}-${cellRef(totalCLRow, 3)}` }
        : 0]
      : []),
  ]);
  netCARow.font = { bold: true };
  netCARow.getCell(2).numFmt = RUPEE_FMT;
  netCARow.getCell(2).fill = TOTAL_FILL;
  if (hasPrev) { netCARow.getCell(3).numFmt = RUPEE_FMT; netCARow.getCell(3).fill = TOTAL_FILL; }

  writeSubLabel('4. Deferred Tax Asset');
  const dtaRow = writeLine('bs_deferred_tax_asset', 'Deferred Tax Asset (Net)');
  writeSubLabel('5. Miscellaneous Expenditure / Other Non-current Assets');
  const otherNcRow = writeLine('bs_other_non_current_assets', 'Other Non-current Assets');

  const totalAppRow = writeSubtotal('TOTAL APPLICATION OF FUNDS', [
    fixedAssetsTotalRow, investmentsRow, netCARow.number, dtaRow ?? 0, otherNcRow ?? 0,
  ]);
  ws.getRow(totalAppRow).eachCell((c, n) => {
    if (n > 1) c.border = { top: { style: 'thin' }, bottom: { style: 'double' } };
  });

  // Balance-check italics row
  ws.addRow([]);
  const balanceCheck = ws.addRow([
    'Balance check (sources − application)',
    { formula: `${cellRef(totalSourcesRow, 2)}-${cellRef(totalAppRow, 2)}` },
    ...(hasPrev ? [{ formula: `${cellRef(totalSourcesRow, 3)}-${cellRef(totalAppRow, 3)}` }] : []),
  ]);
  balanceCheck.font = { italic: true, color: { argb: 'FF6B7280' } };
  balanceCheck.getCell(2).numFmt = RUPEE_FMT;
  if (hasPrev) balanceCheck.getCell(3).numFmt = RUPEE_FMT;

  ws.getColumn(1).width = 56;
  ws.getColumn(2).width = 18;
  if (hasPrev) ws.getColumn(3).width = 18;
}

function buildSimplifiedPL(wb: ExcelJS.Workbook, input: TallyVerticalExportInput) {
  const ws = wb.addWorksheet('Statement of P&L');
  const { report } = input;
  const hasPrev = report.hasPreviousYear;

  ws.addRow([`${input.draft.firm?.firmName ?? '—'}`]).font = { bold: true, size: 12 };
  ws.addRow(['Statement of Profit and Loss for the year ended']).font = { italic: true, color: { argb: 'FF6B7280' } };
  ws.addRow([]);
  const header = ws.addRow(['Particulars', report.currentLabel, ...(hasPrev ? [report.previousLabel] : [])]);
  header.font = { bold: true };
  header.eachCell((c, n) => { if (n > 1) { c.fill = SECTION_FILL; c.alignment = { horizontal: 'right' }; } });
  ws.addRow([]);

  const rowMap = new Map<ScheduleThreeSection, number>();
  const writeLine = (key: ScheduleThreeSection, label: string) => {
    const agg = report.aggregate[key];
    const cur = agg?.current ?? 0;
    const prev = agg?.previous ?? 0;
    if (Math.abs(cur) < 0.01 && Math.abs(prev) < 0.01) return;
    const row = ws.addRow([`  ${label}`, roundInt(cur), ...(hasPrev ? [roundInt(prev)] : [])]);
    row.getCell(2).numFmt = RUPEE_FMT;
    if (hasPrev) row.getCell(3).numFmt = RUPEE_FMT;
    rowMap.set(key, row.number);
  };
  const writeSection = (heading: string) => {
    const r = ws.addRow([heading]);
    r.font = { bold: true };
    r.getCell(1).fill = SECTION_FILL;
  };
  const writeSubtotal = (label: string, keys: ScheduleThreeSection[]) => {
    const refs = keys.map((k) => rowMap.get(k)).filter((r): r is number => typeof r === 'number');
    if (refs.length === 0) {
      const r = ws.addRow([label, 0, ...(hasPrev ? [0] : [])]);
      r.font = { bold: true };
      r.getCell(2).numFmt = RUPEE_FMT;
      if (hasPrev) r.getCell(3).numFmt = RUPEE_FMT;
      return r.number;
    }
    const row = ws.addRow([
      label,
      { formula: refs.map((r) => cellRef(r, 2)).join('+') },
      ...(hasPrev ? [{ formula: refs.map((r) => cellRef(r, 3)).join('+') }] : []),
    ]);
    row.font = { bold: true };
    row.getCell(2).numFmt = RUPEE_FMT;
    row.getCell(2).fill = TOTAL_FILL;
    if (hasPrev) { row.getCell(3).numFmt = RUPEE_FMT; row.getCell(3).fill = TOTAL_FILL; }
    return row.number;
  };

  writeSection('INCOME');
  writeLine('pl_revenue_operations', 'Revenue from Operations');
  writeLine('pl_other_income', 'Other Income');
  const totalIncome = writeSubtotal('Total Income', ['pl_revenue_operations', 'pl_other_income']);

  ws.addRow([]);
  writeSection('EXPENSES');
  writeLine('pl_cost_of_materials', 'Cost of Materials Consumed');
  writeLine('pl_purchases_stock', 'Purchases');
  writeLine('pl_change_inventory', 'Changes in Inventory');
  writeLine('pl_employee_benefits', 'Employee Costs');
  writeLine('pl_finance_costs', 'Finance Costs');
  writeLine('pl_depreciation_amort', 'Depreciation');
  writeLine('pl_other_expenses', 'Other Expenses');
  const totalExp = writeSubtotal('Total Expenses', [
    'pl_cost_of_materials', 'pl_purchases_stock', 'pl_change_inventory',
    'pl_employee_benefits', 'pl_finance_costs', 'pl_depreciation_amort', 'pl_other_expenses',
  ]);

  const pbtRow = ws.addRow([
    'Profit Before Tax',
    { formula: `${cellRef(totalIncome, 2)}-${cellRef(totalExp, 2)}` },
    ...(hasPrev ? [{ formula: `${cellRef(totalIncome, 3)}-${cellRef(totalExp, 3)}` }] : []),
  ]);
  pbtRow.font = { bold: true };
  pbtRow.getCell(2).numFmt = RUPEE_FMT;
  if (hasPrev) pbtRow.getCell(3).numFmt = RUPEE_FMT;

  writeSection('TAX');
  writeLine('pl_tax_current', 'Current Tax');
  writeLine('pl_tax_deferred', 'Deferred Tax');
  const taxTotal = writeSubtotal('Total Tax', ['pl_tax_current', 'pl_tax_deferred']);

  const patRow = ws.addRow([
    'Profit After Tax',
    { formula: `${cellRef(pbtRow.number, 2)}-${cellRef(taxTotal, 2)}` },
    ...(hasPrev ? [{ formula: `${cellRef(pbtRow.number, 3)}-${cellRef(taxTotal, 3)}` }] : []),
  ]);
  patRow.font = { bold: true };
  patRow.eachCell((c, n) => {
    if (n > 1) {
      c.numFmt = RUPEE_FMT;
      c.fill = TOTAL_FILL;
      c.border = { top: { style: 'thin' }, bottom: { style: 'double' } };
    }
  });

  ws.getColumn(1).width = 56;
  ws.getColumn(2).width = 18;
  if (hasPrev) ws.getColumn(3).width = 18;
}
